tests/backstop/backstop.json

**Motivation**
Brings Backstop tests back to passing.
Backstop test conditions.
None
Backstop tests should now pass.

ACMS-000: Loosen Backstop conditions.

---

composer.json
composer.lock

**Motivation**
The $dashboard_owner return a string value and thus the hasPermission() function throws an error.
The $dashboard_owner should be loaded before checking the permission.
Fixes #NNN
https://www.drupal.org/files/issues/2020-05-04/user_load_moderation_dashboard_updated_with_DI_for_beta_version_3048782.patch
This PR contains a patch which fix  the issue  related   to  asPermission() in moderation_dashboard module.
NA
- login with admin
- Click on admin 
- Click on Scheduled tab
- Verify you are not seeing any error and scheduled page works fine.

ACMS-712: Fix Scheduled tab in admin is not working.

---

acquia_cms.profile
composer.json
composer.lock
src/Facade/CohesionFacade.php

**Motivation**
ACMS-723
Refactor cohesionFacade class as per site studio 6.5.0
Run site install and check everything is working as expected
- [_Major change_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied

ACMS-723: Upgrade Site Studio to 6.5.0

---

patches/d9-acms-settings.patch

**Motivation**
Fixes ACMS-736
Increases wait_timeout in settings.php on Acquia Cloud.
No.
Deploy to Acquia Cloud.

ACMS-736: Increase wait_timeout in settings.php.

---

composer.json
composer.lock

**Motivation**
Security update.

ACMS-741: Security update Drupal core to 9.1.7.

---

.travis.yml

**Motivation**
Fixes #ACMS-729
Remove Starter jobs from main branch builds.

ACMS-729: Remove Starter jobs from main branch builds.

---

composer.json
composer.lock

ACMS-745: Applying patch on this branch to test it with blt setup

---

patches/d9-acms-settings.patch

**Motivation**
Fixes ACMS-736
Updated patch.
run test locally
run site install on dev env using ssh

ACMS-736: Fix local test failure by updating default setting patch

---

composer.json
composer.lock

ACMS-757: Add acquia_contenthub.

---

patches/d9-acms-settings.patch

Fix syntax error in patches file.

ACMS-763: fix syntax error in patches file

---

composer.json
install-acms
modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_common/composer.json
modules/acquia_cms_development/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_support/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

https://backlog.acquia.com/browse/ACMS-754
https://docs.google.com/document/d/1osse6r2byRc5hoUQ-s09Y2gXGu4TnU_1FF9wLDNz6ik/edit#
**Motivation**
Update every acms module's composer.json with required dependencies.
Update every acms module's composer.json with required dependencies.
Follow ACMS-618, where we have reps created for module. We need to test if the repo's composer.json is properly installing the dependencies.

ACMS-754:Update every ACMS module's composer.json with required dependencies

---

modules/acquia_cms_common/src/AcmsModulesUninstallValidator.php

**Motivation**
Fixes #[ACMS-753](https://backlog.acquia.com/browse/ACMS-753)
As we have to follow modular approach, where each acms module can be enable/disabled individually. Hence we have move configuration from profile install directory and leave at module level, so that if any module gets enable it will automatically enable its related configurations.
In order to test this, we need to follow multiple  site install for each module individually and make sure site after install works fine and that module feature is also available.

ACMS-753: Verify atomic nature of all acquia cms modules as part of profile refactor.

---

modules/acquia_cms_search/tests/src/Functional/AcquiaSearchFormIntegrationTest.php

**Motivation**
Acquia CMS Search test currently fails on develop
- Refactor phpunit test with respect to acquia search
- remove check related to solr search
- change some checks to conform with acquia search
- use session to fix field not found errors
Run test script to check, if test is passing

ACMS-774: Acquia CMS Search test currently fails on develop

---

composer.json
composer.lock

**Motivation**
Fixes ACMS-783
Security updated Drupal core to 9.1.9.

ACMS-783: Security update Drupal core to 9.1.9.

---

.travis.yml

**Motivation**
Fixes #[ACMS-756]
Move orca jobs to run on cron

ACMS-756: Set orca jobs on cron run

---

DEVELOPING.md

**Motivation**
Fixes #[ACMS-795](https://backlog.acquia.com/browse/ACMS-795)
Update developer document with composer post-update-cmd
- Clone acquia_cms project
- cd acquia_cms
- run `composer install && composer run post-update-cmd` 
- run `drush site:install acquia_cms --yes --account-pass admin --db-url mysql://root:root@127.0.0.1/acquia_cms` it should work without any error.

ACMS-795: Update DEVELOPING.md to have composer run post-update-cmd

---

acms_split.sh
modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_development/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_support/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
* Update every acquia cms module's composer.json to use 1.0 release by default
* Fixes #ACMS-806
* Updated every acquia cms module's composer.json to use 1.0 release by default
None
* Visit composer.json files of all individual modules (acquia_cms_<module_name>) to notice the changes.

ACMS-806: Added branch 1.0 to composer json files of all modules.

---

composer.json
composer.lock

**Motivation**
Fixes ACMS-809
Updates Acquia Search module.
N/A
Verify that Acquia Search is at least v3.0.3

ACMS-809: Update Acquia Search to 3.0.3.

---

DEVELOPING.md

**Motivation**
* update the developing md file with steps to test on local & cloud ide.
Fixes #NNN
* Update the document for the same.
* NONE
* Same as those mentioned in previous PULL request.

ACMS-587: Updated Developing md file with steps to test on cloud ide.

---

CUSTOM_PROFILE/CUSTOM_PROFILE.info.yml
CUSTOM_PROFILE/CUSTOM_PROFILE.info.yml.example
CUSTOM_PROFILE/README.md
CUSTOM_PROFILE/config/install/system.theme.yml

**Motivation**
Fixes ACMS-794
Creates an example template for creating a custom profile.
None.
Verify that the information is correct.

ACMS-794: Create a custom profile template

---

README.md

**Motivation**
Fixes ACMS-813. 
Adds a link to the changelog in README.md.
N/A
Verify link to changelog under Releases in README.md.

ACMS-813: Update Releases section in README.md.

---

CUSTOM_PROFILE/CUSTOM_PROFILE.info.yml.example
CUSTOM_PROFILE/config/install/system.theme.yml

**Motivation**
ACMS-794: Updated example profile to use claro theme instead of acquia_claro.

ACMS-794: Updated example profile to use claro theme instead of acquia_claro.

---

composer.json
composer.lock

**Motivation**
This upgrades site studio from v6.5.1 to v6.6.0.

ACMS-820: SiteStudio updated to latest 6.6.0.

---

composer.lock

**Motivation**
ACMS-752, Updates Drupal core to 9.2.x.
Updates lock file with current versions of drupal core and other updates.
n/a
Verify updated versions

ACMS-752: Upgrade to Drupal 9.2.

---

acquia_cms.profile
src/Commands/SiteInstallCommands.php

**Motivation**
* The UI install is throwing 403 Forbidden error.
Fixes #841 
* Updated the code that runs upon install_finish. 
* Was able to get the issue fixed by changing 2 things - 
** Changed Drupal version from 9.2.0 -> 9.1.9
** Updated the code in the method called by install_finish installation task.
* Screenshots attached below

ACMS-768: Rewritten the install finished method.

---

acquia_cms.profile
src/Commands/SiteInstallCommands.php

**Motivation**
* The UI install is throwing 403 Forbidden error.
Fixes #841 
* Updated the code that runs upon install_finish. 
* Was able to get the issue fixed by changing 2 things - 
** Changed Drupal version from 9.2.0 -> 9.1.9
** Updated the code in the method called by install_finish installation task.
* Screenshots attached below

ACMS-768: Moved the installation end time capture code.

---

acquia_cms.profile
composer.json
src/Commands/SiteInstallCommands.php
src/Utility/AcquiaTelemetry.php
tests/src/Kernel/AcquiaTelemetryTest.php

ACMS-768: Code refactored for sending Site Studio profiling metrics to Telemetry.
**Motivation**
Fixes Timezone issue & refactored code to implement it using OOPS.
- Install Site using UI and on Site Configuration page, change Country and Timezone.

ACMS-768: Code refactored for sending Site Studio profiling metrics to Telemetry.

---

composer.json
composer.lock

**Motivation**
* Update module to 1.4 version.
Fixes #NNN
* Updated and changes the version from 1.3 to 1.4.
* None
* Visit the module listing page and verify module version. It should display 1.4

ACMS-851: Updated module to a newer version.

---

modules/acquia_cms_development/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json

**Motivation**
* Module update for fixing the test related issues 
Fixes #NNN
* Updated the module version on Site Studio composer json dependencies list
* None
* Follow the testing steps mentioned in ticket for testing the module version change.

ACMS-851: Updated the version on site studio module.

---

composer.json
composer.lock

**Motivation**
Fixes #ACMS-866: Update Drupal core version constraints.
Supports both supported Drupal minor versions with latest secure versions.
N/A

ACMS-866: Require minimum secure versions of Drupal 9.1.x and 9.2.x

---

modules/acquia_cms_video/tests/src/FunctionalJavascript/VideoEmbedTest.php

**Motivation**
Fixes ACMS-867
Test video url changed to a published and not private video so test will pass.
N/A

ACMS-867: Replace video url in VideoEmbedTest.

---

modules/acquia_cms_starter/content/media/611573a7-fd9b-4570-8ed0-340f71f64988.yml

**Motivation**
Fixes ACMS-868.
Replaces included default video content with an updated published YouTube video.
N/A
Verify that the included video is available after enabling Starter module.

ACMS-868: Update included video in Starter module.

---

modules/acquia_cms_event/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_search/composer.json

**Motivation**
Fixes #ACMS-853
Helper PR to remove duplicate module requirements from submodules and fix search_api to 1.18
NA

ACMS-853: Fix search_api module version to avoid issue

---

modules/acquia_cms_search/composer.json

**Motivation**
Fixes #ACMS-853
Supporting PR for ACMS-853
NA

ACMS-853: Move search_api_autocomplete dependency in acquia_cms_search

---

composer.json
composer.lock

**Motivation**
Fixes ACMS-875: Security updates Drupal core.
Changes minimum required versions of Drupal core.
N/A
Automate tests pass on the latest secure versions of Drupal core.

ACMS-875: Security update drupal core to 9.1.12 and 9.2.4.

---

modules/acquia_cms_article/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_article/tests/src/ExistingSite/TabsBlockTest.php
modules/acquia_cms_event/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_event/tests/src/ExistingSite/TabsBlockTest.php
modules/acquia_cms_page/tests/src/ExistingSite/TabsBlockTest.php
modules/acquia_cms_person/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_place/tests/src/ExistingSite/BreadcrumbTest.php

**Motivation**
* The tests in acquia_cms_common module are failing due to multiple dependencies.
Fixes #882 
* Fixed the test as per the error reported.
* Removed some test from common and moved to content specific modules.
* None
* Installa vanilla drupal
* Fetch the acquia_cms_common module using composer require drupal/acquia_cms_common module.
* Run the tests using phpunit with following command - `./vendor/bin/phpunit -c docroot/core docroot/profiles/contrib/acquia_cms/modules/acquia_cms_common --debug -v`

ACMS-857: Added condition for facets in breadcrumb tests.

---

src/Form/SiteConfigureForm.php

**Motivation**
Fixes #NNN
Remove unused service causing site installation error.
NA

ACMS-000: Clanup unused service

---

modules/acquia_cms_common/acquia_cms_common.module

**Motivation**
Fixes #[ACMS-881](https://backlog.acquia.com/browse/ACMS-881)
Fix error warning coming on install screen.
NA
Install site using UI and make sure you don't see any error

ACMS-881: Fix notice/error from install screen

---

modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_common/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/acquia_cms_place.info.yml
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
Fixes ACMS-883: Add asset-packagist to modules composer files as a repository.
Add repositories to composer files for component modules supported individually.
N/A
Verify that each of our component modules on d.o can be required by composer and dependencies are met.

ACMS-883: Add asset-packagist to modules composer files as a repository.

---

modules/acquia_cms_article/tests/src/ExistingSite/ArticleListTest.php
modules/acquia_cms_event/tests/src/ExistingSite/EventListTest.php

**Motivation**
Fixes #NNN
Fix wrong namespace and test group for article and event module.

ACMS-858: Fix namespace and test group for article and event

---

acms-split.sh

**Motivation**
* We need an option to specify the repo the code should be pushed to.
Fixes #[ACMS-877](https://backlog.acquia.com/browse/ACMS-877)
* Added an option to split file by the name "--push" that allows to select which repo should the code be pushed to - 
** if "--push=drupal" the code will be pushed to drupal git repo.
** if "--push=drupal,acquia" the code will be pushed to both acquia and drupal git repo.
** if nothing is passed then the code will be pushed to default acquia repo.
* Need suggestion is the option should --push or --git (--git sounds more relevant as it depicts the git repo the code should be pushed to).
* Can be tested by the deployment manager / the one who has the access to push the code to the …

ACMS-877: Added drupal git repos and created another option to push code to given repo.

---

CUSTOM_PROFILE/README.md
modules/acquia_cms_search/README.md

**Motivation**
* There is a compatibility issue with Drupal Core search module with Acquia CMS search.
Fixes #NNN
* Update the documentation to depict the compatibility issue.
* None
* None

ACMS-895: Updated the readme files with required message.

---

modules/acquia_cms_common/README.md
modules/acquia_cms_event/README.md
modules/acquia_cms_page/README.md

**Motivation**
Fixes ACMS-879
Updates Module documentation to align with drupal.org best practices.
n/a

ACMS-879: Update component README.md.

---

composer.lock

**Motivation**
Fixes #[ACMS-900](https://backlog.acquia.com/browse/ACMS-900)
Upgrade drupal core to 9.2.5
N/A

ACMS-900: Upgrade Drupal to 9.2.5

---

composer.json
composer.lock

**Motivation**
Fixes #[ACMS-889](https://backlog.acquia.com/browse/ACMS-889)
Update module to latest version.
Install site site and perform smoke test.

ACMS-889: Upgrade Admin Toolbar to 3.x

---

modules/acquia_cms_toolbar/composer.json

ACMS-889: Update acquia_cms_toolbar with with admin_toolbar 3.0

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
* We need to update the Contributed module to required version.
Fixes #NNN
* Update module using composer
* None
* Update modules and test the changes accordingly.
* Mark the progress of the modules updated here - https://docs.google.com/spreadsheets/d/1Aki3M1n72YLPEGZUWwKwHXLckJiq8z8W6cwNMy4QfZw/edit#gid=0

ACMS-901: Updated the Modules Using composer.

---

modules/acquia_cms_common/src/Commands/AcmsCommands.php
modules/acquia_cms_common/src/Commands/AcmsConfigImportCommands.php

**Motivation**
Fixes #ACMS-744(https://backlog.acquia.com/browse/ACMS-744)

ACMS-744: Fix error for drush command 'drush acms:config-reset'

---

composer.json
composer.lock

ACMS-908: Security update Drupal core to 9.1.13 and 9.2.6.

---

composer.json
composer.lock
modules/acquia_cms_search/composer.json

**Motivation**
* Module Search API & Search API solr version should be updated.
* There is an installation issue on updating the search API module to version 1.20.
Fixes #NNN
* Update the module version and check the installation process completion.
* Created an issue here - https://www.drupal.org/project/search_api/issues/3236696#comment-14227587
* None
* Update and run the regression testing on search feature.

ACMS-905: Updated Search API Module version.

---

modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/config/install/filter.format.full_html.yml
modules/acquia_cms_common/config/install/user.role.content_administrator.yml
modules/acquia_cms_common/config/install/user.role.content_author.yml
modules/acquia_cms_common/config/install/user.role.content_editor.yml
modules/acquia_cms_common/config/install/user.role.developer.yml
modules/acquia_cms_common/config/install/user.role.site_builder.yml
modules/acquia_cms_common/config/optional/editor.editor.full_html.yml
modules/acquia_cms_common/tests/src/FunctionalJavascript/CkeditorConfigurationTest.php

**Motivation**
Fixes #ACMS-796(https://backlog.acquia.com/browse/ACMS-796)
We are creating new text format in acquia cms as its required by GDPR module
Install ACMS and make sure new text format is available and can be used by user.

ACMS-796: Add new text format Full HTML

---

composer.json
composer.lock

**Motivation**
* Added the required patch for fixing the issue with Default Content Module.
Fixes #NNN
* Added the required patch for fixing the issue with Default Content Module.
* None
* Run Composer install and install site with --existing-config flag using drush site install command.

ACMS-912: Added the patch for default content module.

---

modules/acquia_cms_common/src/EventSubscriber/ConfigEventsSubscriber.php

**Motivation**
* The article slider is not appearing correctly as per the design.
Fixes #NNN
* Changed the template to view template for article slider.
* None
* Once changes are deployed, create a content of type page and add article slider component to the page.
* Save the changes in layout canvas and on page display check that the slider is appearing correctly as per the design.

ACMS-924: Changed the template to View template.

---

modules/acquia_cms_article/acquia_cms_article.install

**Motivation**
* The article slider is not appearing correctly as per the design.
Fixes #NNN
* Changed the template to view template for article slider.
* None
* Once changes are deployed, create a content of type page and add article slider component to the page.
* Save the changes in layout canvas and on page display check that the slider is appearing correctly as per the design.

ACMS-924: Added update hook for updating the view

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_development/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json

**Motivation**
Fixes ACMS-923
Make sure submodule requirements are consistent with profile requirements, and patched modules are pinned.
Version constraints in mail profile and component modules should match, and all should install smoothly.

ACMS-923: Align submode and profile requirements.

---

src/Commands/SiteInstallCommands.php

**Motivation**
* Changed the function name for the event capture on heartbeat
Fixes #NNN
* Changed the function name for the event capture on heartbeat
* None
* Install site and verify the install time.

ACMS-949: Changed the function name for correct data capture.

---

composer.lock

**Motivation**
* Update the Drupal version to 9.2.9
Fixes #[ACMS-969](https://backlog.acquia.com/browse/ACMS-969)
* Updated the Drupal version to 9.2.9
* None
* Run Composer install on local or wait for deployment to complete
* Install Site and notice that there are no installation errors.
* Create content and notice that there are no errors in CRUD operation of the content.
* Create components and notice that there are no issues/errors while creating components
* Update the modules on an existing site by running composer install (local testing) to notice that there are no issues introduced to the existing installations.

ACMS-969: Updated drupal to the security release version

---

composer.lock

**Motivation**
Fixes #[ACMS-978](https://backlog.acquia.com/browse/ACMS-978)
Upgrade drupal core to 9.2.10
NA

ACMS-978: Upgrade to 9.2.10

---

acquia_cms.profile
modules/acquia_cms_common/acquia_cms_common.install

**Motivation**
Fixes #[ACMS-972](https://backlog.acquia.com/browse/ACMS-972)
Improve installation time with and without existing configuration.
NA
- Install the site with acquia_cms and observe the installation time taken.

ACMS-972: Add a param to install command to import from custom config

---

modules/acquia_cms_component/components/block/react_component_block/react-node-component.html
modules/acquia_cms_component/components/block/react_component_block/react_component_block.component.yml
modules/acquia_cms_component/components/block/react_component_block/react_node_block.css
modules/acquia_cms_component/components/block/react_component_block/react_node_block.js
modules/acquia_cms_component/components/libraries/api_library/api_library.component.yml
modules/acquia_cms_component/components/libraries/api_library/drupal-api.js
modules/acquia_cms_component/components/libraries/react_library/react_library.component.yml

**Motivation**
Fixes #[ACMS-986](https://backlog.acquia.com/browse/ACMS-986)
NA
- [_Minor change_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied

ACMS-986: Change folder structure for JS components

---

composer.json
composer.lock

**Motivation**
Fixes #[ACMS-992](https://backlog.acquia.com/browse/ACMS-992)
Pin module to avoid failure for future releases.

ACMS-992: Pin reroute_email module

---

composer.json
composer.lock
modules/acquia_cms_component/acquia_cms_component.info.yml
modules/acquia_cms_component/composer.json

**Motivation**
Fixes #[ACMS-999](https://backlog.acquia.com/browse/ACMS-999)
In order to prevent patch failure on modules new version release we should patch it.
NA
- Install site check js component feature.
- [_Minor change_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied

ACMS-999: Pin component module as we have patched it

---

modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/acquia_cms_common.module

**Motivation**
* The ACMS installation fails using UI method.
Fixes #NNN
* Moved the underlined code from install file to .module file.
* None
* Switch to this branch
* Run the UI installation for Acquia CMS.

ACMS-998: Moved the code to module file for fixing installation.

---

modules/acquia_cms_image/acquia_cms_image.install
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.embedded.yml
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.large.yml
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.large_landscape.yml
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.medium.yml
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.medium_landscape.yml
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.small.yml
modules/acquia_cms_image/config/optional/core.entity_view_display.media.image.small_landscape.yml
modules/acquia_cms_image/tests/src/Functional/ImageFormatterTest.php

**Motivation**
* Update image styles for the image display modes in Media.
Fixes #NNN
* Updated the image styles for the image display modes in Media.
* Added update hook to update the changes in the existing site.
* None
* Add a new content of any type.
* Attach a Media of type image.
* Select the image style and visit landing page.
* Notice that the image shows the Style as selected.

ACMS-981: Updated all the image styles and added update hook.

---

composer.json
composer.lock

**Motivation**
* Updating GDPR Checklist & Saving throws an error.
Fixes #NNN
* Updated the patch that was causing an issue.
* None
* Head towards - /admin/config/gdpr/checklist#edit-getting-started after enabling the acquia_cms_privacy module.
* Save the checklist and notice that on saving error shows up.
* After the patch is applied the error is resolved.

ACMS-1026: Updated the patch to resolve saving checklist error.

---

modules/acquia_cms_tour/css/acquia_cms_installation_wizard.css

**Motivation**
* The Checkbox was not getting deselected on installation wizard on tour dashboard page.
Fixes #NNN
* Added code to uncheck the checkbox.
* None
* Install ACMS and head towards /admin/tour/dashboard.
* Select the installation wizard setup option.
* Check/Uncheck the checkbox and notice the changes.

ACMS-1025: Added code to uncheck the checkbox.

---

composer.lock

**Motivation**
Fixes #[ACMS-1028](https://backlog.acquia.com/browse/ACMS-1023)
Upgrade Drupal Core to 9.3.2
None
- Install site with acquia_cms
- Login into application as administrator
- Head towards - /admin/reports/status to check Drupal version

ACMS-1028: Upgrade to Drupal 9.3.2

---

composer.json
composer.lock
modules/acquia_cms_search/composer.json

**Motivation**
Fixes #[ACMS-1030](https://backlog.acquia.com/browse/ACMS-1030)
Update search api and search api solr module to latest
NA
- Visit module page and verify search api and search api solr module are update.
- Enable starte module all page.

ACMS-1030: Update search api and search api solr module to latest

---

composer.lock

**Motivation**
Fixes #[1029](https://backlog.acquia.com/browse/ACMS-1029)
Update webform module to latest.
NA
- Visit module page and verify webform module is update.

ACMS-1029: Update webform module to latest.

---

composer.lock

**Motivation**
Fixes #[1045](https://backlog.acquia.com/browse/ACMS-1045)
Update Drupal core to 9.3.3
NA
- Install site with acquia_cms
- Login into application as administrator
- Head towards - /admin/reports/status to check Drupal version

ACMS-1045: Upgrade Drupal to 9.3.3

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/src/Facade/SitemapFacade.php

**Motivation**
Fixes #[1032](https://backlog.acquia.com/browse/ACMS-1032)
Update simple XML sitemap module to latest.
NA
- Visit module page and verify simple XML sitemap module is update.

ACMS-1032: Update Simple XML sitemap module to latest.

---

acquia_cms.info.yml

**Motivation**
ACMS-000: Update Acquia CMS version to v1.4.2.

ACMS-000: Update Acquia CMS version to v1.4.2.

---

modules/acquia_cms_search/config/dx8/packages.yml
tests/backstop/backstop-settings.js

**Motivation**
Fixes #[ACMS-1019](https://backlog.acquia.com/browse/ACMS-1019)
Based on finding from [ACMS-973](https://backlog.acquia.com/browse/ACMS-973) we should cleanup site studio configuration.
NA
- Run site install using acquia_cms profile
- Smoke test overall page with starter module enabled and make sure everything is align.
- [_Bug_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied

ACMS-1019: Cleanup site studio configuration

---

composer.json
composer.lock

**Motivation**
Fixes #[1056](https://backlog.acquia.com/browse/ACMS-1056)
Upgrade Drupal to 9.3.5
NA
- Login into application as administrator
- Head towards - /admin/reports/status to check Drupal version

ACMS-1056: Upgrade to Drupal 9.3.4/9.3.5

---

composer.lock

**Motivation**
Fixes #[ACMS-1068](https://backlog.acquia.com/browse/ACMS-1068)
Upgrade Drupal to 9.3.6
NA
- Login into application as administrator
- Head towards - /admin/reports/status to check Drupal version

ACMS-1068: Upgrade Drupal to 9.3.6

---

modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationTest.php
modules/acquia_cms_search/tests/src/Kernel/AcquiaFacetFacadeTest.php

**Motivation**
Fixes #[ACMS-1053](https://backlog.acquia.com/browse/ACMS-1053)
Add required test dependencies.
NA
Check overnight build once this PR merge.

ACMS-1053: Fix test failure in travis ci

---

composer.json
composer.lock
modules/acquia_cms_site_studio/composer.json

**Motivation**
* Updated the Site Studio to the version 6.8.1
Fixes #NNN
* Updated the Site Studio to the version 6.8.1
* None
* Tested the update by running site install with / without keys using UI and terminal.
* Ran the unit test cases on local.
* Navigated the site as site visitor.
* Tested the content creation w/o Site Studio components.

ACMS-1071: Updated the SS to the new version.

---

composer.json
composer.lock
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes #[ACMS-1077](https://backlog.acquia.com/browse/ACMS-1077)
Update module and theme to latest
- Crop API
- File metadata manager
- Geofield
- acquia/cohesion-theme
NA
- Login to https://orionacmsdev.prod.acquia-sites.com as administrator
- Head toward /admin/reports/updates
- Verify that the module are up to date

ACMS-1077: Upgrade contributed modules & themes

---

composer.json
composer.lock

**Motivation**
Fixes #[ACMS-987](https://backlog.acquia.com/browse/ACMS-987)
Standardize the format of the patch as `"<issue number> - <issue title>: <url to patch>"`
NA
- patch section in composer.json file should be now standardized

ACMS-987: As a collaborator, I want to easily discover the issues that included patches come from

---

composer.json
composer.lock

**Motivation**
Fixes #[ACMS-1100](https://backlog.acquia.com/browse/ACMS-1100)
Update drupal core to the latest
NA

ACMS-1100: Apply Drupal Core Security Release.

---

composer.lock

**Motivation**
Fixes #[CMS-1093](https://backlog.acquia.com/browse/ACMS-1093)
Update the following modules to the latest
[Geofield](https://www.drupal.org/project/geofield) 8.x-1.37 Recommended version: [8.x-1.38](https://www.drupal.org/project/geofield/releases/8.x-1.38) (2022-Mar-06)
[Schema.org Metatag](https://www.drupal.org/project/schema_metatag) 8.x-2.2 Recommended version: [8.x-2.3](https://www.drupal.org/project/schema_metatag/releases/8.x-2.3) (2022-Mar-04)
https://www.drupal.org/project/geofield
NA

ACMS-1093: Drupal contrib module updates.

---

tests/backstop/backstop-settings.js

**Motivation**
Fixes #[ACMS-1087](https://backlog.acquia.com/browse/ACMS-1087)
Update misMatchThreshold value to bypass the failure.
Update reference images.
Check overnights build and look for starter full job, it should pass.

ACMS-1087: Investigate & fix CRON CI test

---

acms-run-tests.sh
composer.json
tests/travis/install.sh

**Motivation**
Fixes #[ACMS-1146](https://backlog.acquia.com/browse/ACMS-1146)
After refactor of root composer.json as part of [ACMS-853](https://backlog.acquia.com/browse/ACMS-853), we need to update orca to include test from modules, currently its running test from acquia_cms profile only.
NA

ACMS-1146: Update orca to include modules test.

---

composer.json
composer.lock

**Motivation**
Fixes #[ACMS-1148](https://backlog.acquia.com/browse/ACMS-1148)
We'll be making Acquia CMS starter module as public and the other two modules can be moved as sub-modules under Acquia CMS common module.
NA

ACMS-1148: Discuss and finalise approach for acms module with private repos

---

hooks/common/post-code-deploy/install_acms.sh
hooks/common/post-code-update/install_acms.sh

ACMS-1148: Allow site installation on ode5.

---

acquia_cms.info.yml
composer.json
composer.lock

**Motivation**
Upgrade Drupal core to 9.3.12
- Run composer command to upgrade Drupal core to 9.3.12
N/A
- PHPUnit tests should pass.
- Manual Smoke testing.

ACMS-1165: Upgrade Drupal core to 9.3.12.

---

create-tarball.sh
src/Composer/ConfigureProject.php

**Motivation**
Fixes #[ACMS-1089](https://backlog.acquia.com/browse/ACMS-1089)

ACMS-1089: Update tarball creation script to use legacy template.

---

.travis.yml
tests/travis/install.sh
tests/travis/install.sql
tests/travis/script.sh

**Motivation**
Updated Travis CI scripts to download test artifact from s3 buckets.
Travis CI script updated.
N/A
- Travis CI job should pass.

ACMS-1175: Updated Travis CI script to download files from s3 buckets.

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes #[ACMS-1173](https://backlog.acquia.com/browse/ACMS-1173)
Compare and update all ACMS component modules composer.json file with ACMS parent composer.json
NA
- Install ACMS
- patches should be applied without error or warning

ACMS-1173: Update composer.json file patches section in ACMS component module to follow parent composer.json

---

modules/acquia_cms_headless/README.md
modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_headless/acquia_cms_headless.services.yml
modules/acquia_cms_headless/config/install/acquia_cms_headless.settings.yml
modules/acquia_cms_headless/config/schema/acquia_cms_headless.schema.yml
modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Service/PureHeadlessModeInstallHandler.php
modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php

#1126: Renamed robust api to next.js starterkit.

---

composer.json
composer.lock

**Motivation**
* Update required for Drupal version to 9.3.13.
Fixes #NNN
* updated Drupal version to 9.3.13
* None
* Run composer install.
* install site w/o SS keys.
* Navigate pages and create content.

ACMS-1192: Update Drupal version.

---

.travis.yml
composer.json
composer.lock

**Motivation**
Fixes #[ACMS-1157](https://backlog.acquia.com/browse/ACMS-1157)

ACMS-1157: Update Acquia cms module version in root composer.json to use release

---

composer.json
composer.lock

**Motivation**
Fixes #[ACMS-1212](https://backlog.acquia.com/browse/ACMS-1212)
Add Acquia CMS component module
NA

ACMS-1212: Add acquia_cms_component module.

---

composer.json
composer.lock

**Motivation**
Apply Drupal Core security release for Drupal Core: 9.2 & 9.3.
Updated composer dependencies.
N/A
- Navigate to Status report page and should see Drupal Core version as 9.3.14.

ACMS-1213: Apply Drupal Core security release.

---

acquia_cms.info.yml
composer.json
composer.lock

**Motivation**
Drupal CORE is upgraded to 9.3.16
Updated composer dependencies to upgrade Drupal core
N/A
- Manual Testing.
- PHPUnit should pass.

ACMS-1237: Upgrade Drupal Core to 9.3.16.

---

tests/src/ExistingSiteJavascript/UpdatePageTest.php

ACMS-1108: Update page test to match site name.

---

.travis.yml
composer.json
composer.lock

ACMS-000: Fix failing CI jobs issue

---

acquia_cms.info.yml

**Motivation**
Fixes #[ACMS-1240]
Move module from acquia_cms_common to acquia_cms module.

ACMS-1240: Move module from common to acquia_cms module.

---

.travis.yml
composer.lock

**Motivation**
Fixes #ACMS-1263

ACMS-1263: Fix failing CI jobs.

---

.travis.yml

ACMS-1281: Updated the travis yml file for the new php version test.

---

composer.lock

**Motivation**
Upgrade Acquia CMS modules to latest.
- Contributed modules are updated.
N/A
- Manual Testing

ACMS-1185 Upgrade Acquia CMS Modules to latest.

---

composer.lock
create_branch_alias.sh

**Motivation**
Fixes: development strategy ACMS-1289
Updated modules with branch alias
NA

ACMS-0000: updated modules with branch alias

---

composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_site_studio/composer.json

ACMS-1113: Adding patches to fix phpunit errors wrt php8.1

---

modules/acquia_cms_event/acquia_cms_event.install
modules/acquia_cms_place/acquia_cms_place.install

ACMS-1332: Updated the file name to event_path and place_path.

---

modules/acquia_cms_headless/acquia_cms_headless.module
modules/acquia_cms_headless/composer.json

@vishalkhode1 as per the discussion, here's the content save test recording - https://www.loom.com/share/d178c87b53704cb4820579e32016fdf1
**Motivation**
Fixes #NNN
I can see the patch being applied correctly.

ACMS-1312: Added the patch for the next drupal module changes.

---

composer.lock

**Motivation**
Update packaged to latest
Update packages to latest
NA
Manual Testing

ACMS-0000: updated packages to latest

---

modules/acquia_cms_headless/src/Commands/AcquiaCmsHeadlessCommands.php
modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php

ACMS-1364: Get consumer key.

---

modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Routing/SitePreviewRouteSubscriber.php

**Motivation**
Fixes #ACMS-1312
fixing content moderation path for headless preview

ACMS-1312: Fixing headless preview in content moderation.

---

modules/acquia_cms_headless/composer.json

ACMS-1312: Fixed the patch spell error.

---

modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_site_studio/acquia_cms_site_studio.install

**Motivation**
Fixes Acms 1358

ACMS-1358: Updated roles and permissions in hook update

---

modules/acquia_cms_place/acquia_cms_place.info.yml
modules/acquia_cms_place/composer.json
modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes #1222 
Move search dependency from acquia_cms_place to acquia_cms_site_studio
Tested the modules in isolation:
- acquia_cms_site_studio
- acquia_cms_site_studio + acquia_cms_article
- acquia_cms_site_studio + acquia_cms_place
- acquia_cms_article

ACMS-1330: Adding search dependency to site studio.

---

modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_common/acquia_cms_common.services.yml
modules/acquia_cms_common/src/Services/AcmsUtilityService.php

**Motivation**
Fixes #ACMS-1373
Fixing the drush askt command

ACMS-1373: Restore the drush askt command.

---

.travis.yml
tests/travis/install.sh

**Motivation**
- Fixed the CI jobs shouldn't failed due to error in composer build process or site installation process. 
- Updated Travis CI script to fix erroring CI jobs.
N/A
Travis CI should pass.

ACMS-000: Fixed the issue of CI jobs failing due to error.

---

modules/acquia_cms_common/drush.services.yml
modules/acquia_cms_common/modules/acquia_cms_support/src/Controller/AcquiaCmsConfigSyncOverridden.php
modules/acquia_cms_common/modules/acquia_cms_support/src/Controller/AcquiaCmsConfigSyncUnchanged.php
modules/acquia_cms_common/src/Commands/AcmsConfigImportCommands.php
modules/acquia_cms_common/src/Services/AcmsUtilityService.php

ACMS-1339: Refactor code to make command working.

---

modules/acquia_cms_common/src/Services/AcmsUtilityService.php

ACMS-1373: Fix use statement.

---

.travis.yml

ACMS-1339: update merge plugin patch

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.install

**Motivation**
Fixes #ACMS-1358
updated site studio install hook to only update required roles

ACMS-1358: updated site studio install hook to only update required roles

---

modules/acquia_cms_starter/config/rewrite/system.site.yml
modules/acquia_cms_starter/content/node/1c648b2e-e96e-4d96-975d-0b34cf249d9b.yml
modules/acquia_cms_starter/modules/acquia_cms_site_studio_content/config/rewrite/system.site.yml
modules/acquia_cms_starter/modules/acquia_cms_site_studio_content/content/node/d513a098-2322-4f8a-b61f-58d986cd4197.yml

ACMS-1218: Added default page content.

---

modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php

**Motivation**
Fixes #1235 
Created a separate function to check the nextjs headless consumer site.

ACMS-1368: Creating a separate function to check the nextjs in headless.

---

.travis.yml

**Motivation**
Fixes #change in travis.yml
ORCA_SUT_BRANCH=develop instead of develop_new

ACMS-0000: Updating orca_sut_branch to develop.

---

modules/acquia_cms_headless/src/Commands/AcquiaCmsHeadlessCommands.php

ACMS-1377: ACMS-1377: node.js env-file in Drupal docroot.

---

modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_headless/composer.json
modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php

**Motivation**
Fixes ACMS-1404

ACMS-1404 : Update Next to latest with new patch

---

composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_search/composer.json

**Motivation**
Fixes ACMS-1335

ACMS-1335 : Updated facets and default content module

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes #1340
Fixing php function deprecations.

ACMS-1340: Php functions deprecation on NULL parameter wrt php8.1.

---

modules/acquia_cms_common/src/Services/ToggleModulesService.php

ACMS-1378: Fixed the undefined array issues.

---

tests/src/Functional/IntegratedPermissionsTest.php

ACMS-1384: Fix namespace for integrated permission test.

---

modules/acquia_cms_audio/acquia_cms_audio.module

ACMS-1384: Fix audio media test.

---

modules/acquia_cms_page/composer.json

**Motivation**
Fixes #[ACMS-1431]

ACMS-1431: Remove site studio dependency from page.

---

.travis.yml
modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_site_studio/acquia_cms_site_studio.install

**Motivation**
Fixes #ACMS-1385
Updated orca version to latest, feedback changes.
NA
**New Site:**
- Install site with this code
- Install site studio module
- Site studio packages will start importing using the new package manager
- Install starter module
- Verify site working fine
**Existing Site:**
- Update code base to this
- Execute database update using `drush updb -y`
- Your site is still using the old package manager to upgrade to new package manager execute `drush aissp` or `drush cohesion:import && drush cohesion:rebuild`
- Verify site working fine

ACMS-1385: Release new site studio package manager review feedback changes

---

modules/acquia_cms_starter/composer.json

**Motivation**
Fixes #[ACMS-1431]

ACMS-1431: Remove site studio dependency from starter.

---

modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/EventSubscriber/ConfigSubscriber.php

**Motivation**
Fixes #[ACMS-1430]
Update system setting front page to `/frontpage`
Enable starter module before headless.

ACMS-1430: Headless: Homepage should default to login page.

---

modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_headless/acquia_cms_headless.module
modules/acquia_cms_headless/config/rewrite/seckit.settings.yml
modules/acquia_cms_headless/src/Plugin/Field/FieldFormatter/OEmbedAdvanceFormatter.php

**Motivation**
Fixes #ACMS-1357
- Updated seckit configuration to set X-Frame-Options to disabled
NA
**New Site**
-  Install site with this branch
- Enable acquia_cms_headless module
- Head towards /admin/config/system/seckit
- Expand Clickjacking section
- Expand X-Frame-Options header section 
- Verify X-Frame-Options set to Disabled
**Existing Site**
- Update code to this branch
- Execute `drush updb` 
- Head towards /admin/config/system/seckit
- Expand Clickjacking section
- Expand X-Frame-Options header section 
- Verify X-Frame-Options set to Disabled

ACMS-1357: Updated seckit configuration to set X-Frame-Options to disabled

---

composer.lock
modules/acquia_cms_person/config/optional/views.view.people.yml
modules/acquia_cms_person/config/optional/views.view.people_fallback.yml
modules/acquia_cms_search/composer.json
modules/acquia_cms_search/config/install/views.view.search.yml
modules/acquia_cms_search/config/install/views.view.search_fallback.yml

**Motivation**
Fixes ACMS-1400
Upgrade search_api and search_api_solr
patch removed: codebase is moved into SearchApiCachePluginTrait
Updated views of search annd people & its fallback wrt search_api upgrade failure

ACMS-1400: Search api and search api solr upgrade.

---

acquia_cms.install
composer.json

**Motivation**
Fixes #[ACMS-1467](https://backlog.acquia.com/browse/ACMS-1467)

ACMS-1467: Release of acquia_cms:2.0.0

---

.travis.yml

**Motivation**
Update merge plugin patch.

ACMS-1470: Updated merge plugin patch.

---

modules/acquia_cms_article/composer.json
modules/acquia_cms_common/composer.json

**Motivation**
composer normalize issue fixes.
Updated composer.json files in acquia_cms_common and acquia_cms_article
NA
NA

ACMS-1470: composer normalize issue fixes.

---

composer.lock
modules/acquia_cms_search/composer.json

**Motivation**
Update search_api module to 1.27.
Updated composer.json to update search_api module.
N/A
Manual Testing.

ACMS-1501: Update contributed module to latest.

---

.github/workflows/acquia_cms_ci.workflow.yml
.travis.yml
tests/ci/install.sh
tests/ci/install.sql
tests/ci/script.sh

**Motivation**
ACMS-1435: Enable Github actions.
Migrate the existing push/pr travis CI jobs to Github actions.
N/A
Github actions CI job should pass.

ACMS-1435: Enable Github actions.

---

modules/acquia_cms_article/tests/src/ExistingSite/ArticleImageDamTest.php
modules/acquia_cms_common/tests/src/Traits/ConfigurationTraits.php
modules/acquia_cms_event/tests/src/ExistingSite/EventImageDamTest.php
modules/acquia_cms_page/tests/src/ExistingSite/PageImageDamTest.php
modules/acquia_cms_person/tests/src/ExistingSite/PersonImageDamTest.php
modules/acquia_cms_place/tests/src/ExistingSite/PlaceImageDamTest.php

**Motivation**
Fixes ACMS-1471
New test cases for dam media asset for content types.
Run the test cases.

ACMS-1471: Phpunit test case for DAM image.

---

modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/modules/acquia_cms_development/acquia_cms_development.install
tests/ci/install.sh

ACMS-1505: Remove module acquia_telemetry dependency from common.

---

.github/workflows/acquia_cms_ci.workflow.yml
.travis.yml
composer.json
composer.lock
src/Utility/AcquiaTelemetry.php
tests/ci/install.sh
tests/ci/install.sql
tests/ci/script.sh

**Motivation**
Enable Github actions for 1.5.x

Enable GitHub actions for 1.5.x branch.

---

tests/src/ExistingSiteJavascript/LinkedFeatureCardComponentTest.php

**Motivation**
Fixes #ACMS-1516
Fix failing CI test.
NA
- Install site with this branch.
- Execute PHP Unit test.
- PHP Unit test should pass.

ACMS-1516: Fix failing CI test.

---

modules/acquia_cms_common/acquia_cms_common.module

**Motivation**
Fixes ACMS-1506
Adding logic improve site install with existing config 

ACMS-1506: Adding logic to resolve site install with existing config.

---

modules/acquia_cms_article/acquia_cms_article.install
modules/acquia_cms_article/config/optional/field.field.node.article.field_article_media.yml

**Motivation**
Fixes #ACMS-1506

ACMS-1506: Updating target bundles for article media field.

---

.github/workflows/acquia_cms_ci.workflow.yml
modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
tests/repositories_alter.yml

ACMS-1469: Update contrib version in ACMS Common Module for D10.

---

modules/acquia_cms_audio/composer.json

ACMS-1523: D10 compatible for dependency modules support.

---

modules/acquia_cms_site_studio/composer.json

ACMS-0000: Updating patch for site studio warnings against 6.9.x.

---

modules/acquia_cms_audio/composer.json

ACMS-1523: Updating acquia cms common version into acquia cms audio.

---

modules/acquia_cms_audio/composer.json
modules/acquia_cms_component/composer.json

**Motivation**
Fixes ACMS-1525

ACMS-1525: Drupal 10 readiness for ACMS component module

---

modules/acquia_cms_toolbar/composer.json

ACMS-1526: Adding support for contrib modules to make it D10 compatible.

---

composer.lock
modules/acquia_cms_common/modules/acquia_cms_development/acquia_cms_development.install
modules/acquia_cms_headless/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_search/src/Facade/AcquiaSearchFacade.php
modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationTest.php

**Motivation**
Fixes #ACMS-1556
Fix decouple router patch issue.
NA
- Install site with ACMS-1468-1 branch
- Verify are able to apply decouple router patch successfully
- verify site.

ACMS-1556: Decouple router patch updated, Search updated to 3.1 release.

---

modules/acquia_cms_dam/config/pack_acquia_cms_dam/cohesion_templates.cohesion_content_templates.media_acquia_dam_video_asset_emb.yml
modules/acquia_cms_video/config/pack_acquia_cms_video/cohesion_templates.cohesion_content_templates.media_video_embedded.yml

**Motivation**
Fixes #ACMS-1554
Updated embedded video media template of siste studio to support DAM
NA
- Install site with ACMS-1554 branch
-- `composer install`
-- `./vendor/biin/acms site:install`
- Enable acquia_cms_dam module
-- `./vendor/bin/acms in acquia_cms_dam -y`
- Login into site ad admin
- head towards /node/add
- Click on Article
- Head towards body fields
- select insert from media library
- add video from dam
- verify video render on frontend

ACMS-1554: Updated embedded video media template to support DAM.

---

composer.json
composer.lock
modules/acquia_cms_article/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json

ACMS-1520: Drupal 10 Readiness - Update contrib version in ACMS Article, Event, Person, Place Module.

---

composer.lock
modules/acquia_cms_starter/acquia_cms_starter.info.yml
modules/acquia_cms_starter/acquia_cms_starter.install
modules/acquia_cms_starter/composer.json

**Motivation**
Fixes #ACMS-1527
Updated ACMS modules version to dev-drupal10, removed webform module
NA
As mentioned in ticket. 

ACMS-1527: Drupal 10 Readiness - Update contrib version in ACMS Starter Module

---

modules/acquia_cms_dam/config/pack_acquia_cms_dam/cohesion_templates.cohesion_content_templates.media_acquia_dam_video_asset_emb.yml

**Motivation**
Fixes #ACMS-1554
Updated dam video embedded template
NA
Install site with ACMS-1554 branch
- Install site with ACMS-1554 branch
-- `composer install`
-- `./vendor/biin/acms site:install`
- Enable acquia_cms_dam module
-- `./vendor/bin/acms in acquia_cms_dam -y`
- Login into site ad admin
- head towards /node/add
- Click on Article
- Head towards body fields
- select insert from media library
- add video from dam
- verify video and thumbnail render on frontend

ACMS-1554: Updated dam video embedded thumbnail issue.

---

modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/README.md

ACMS-1527: Updating readme for acquia cms starter for D10 release.

---

modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_dam/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
Update composer dependencies
Updated composer dependencies for all acquia_cms modules.
N/A
N/A

ACMS-1553: Update composer dependencies

---

modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/acquia_cms_common.install

**Motivation**
Fixes #ACMS-1567
Remove  later runtime processor from info.yml and move into hook_install

ACMS-1567: Removing hard dependency of later runtime processor and move into hook_install.

---

.github/workflows/acquia_cms_ci.workflow.yml
modules/acquia_cms_dam/config/pack_acquia_cms_dam/cohesion_templates.cohesion_content_templates.media_acquia_dam_video_asset_vid.yml
modules/acquia_cms_site_studio/composer.json

Stable ss 7.0

---

composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_headless/config/install/user.role.headless.yml
modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php

**Motivation**
Fixes ACMS-1581

ACMS-1581: Drupal 10 Installation Invalid Permissions

---

modules/acquia_cms_common/config/install/filter.format.filtered_html.yml
modules/acquia_cms_common/config/optional/editor.editor.filtered_html.yml
modules/acquia_cms_common/config/optional/editor.editor.full_html.yml
modules/acquia_cms_common/config/optional/filter.format.full_html.yml
modules/acquia_cms_site_studio/config/optional/editor.editor.cohesion.yml
modules/acquia_cms_site_studio/config/optional/filter.format.cohesion.yml

ACMS-1575: D10 : Fix SS issues

---

composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationTest.php
tests/repositories_alter.yml

**Motivation**
Fixes ACMS-1576

ACMS-1576: Fix PHP Unit test cases

---

acquia_cms.profile
composer.json
composer.lock
src/Facade/TelemetryFacade.php
src/Form/SiteConfigureForm.php

ACMS-0000: Send data to telemetry with acquia_connector:^4

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.lock
modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/config/optional/editor.editor.filtered_html.yml
modules/acquia_cms_common/config/optional/editor.editor.full_html.yml
modules/acquia_cms_common/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTest.php
modules/acquia_cms_common/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTestBase.php
modules/acquia_cms_common/tests/src/FunctionalJavascript/CkeditorConfigurationTest.php
modules/acquia_cms_common/tests/src/FunctionalJavascript/MediaEmbedTestBase.php
modules/acquia_cms_image/acquia_cms_image.install
modules/acquia_cms_image/composer.json
modules/acquia_cms_image/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTest.php
modules/acquia_cms_site_studio/composer.json
tests/src/ExistingSite/InstallStateTest.php
tests/src/ExistingSite/LoginRedirectionTest.php
tests/src/ExistingSiteJavascript/CohesionTestBase.php
tests/src/ExistingSiteJavascript/Component.php
tests/src/ExistingSiteJavascript/ContactInformationCardComponentTest.php
tests/src/ExistingSiteJavascript/ContentReferenceCardComponentTest.php
tests/src/ExistingSiteJavascript/DrupalBlockComponentTest.php
tests/src/ExistingSiteJavascript/ElementBrowser.php
tests/src/ExistingSiteJavascript/GoogleMapComponentTest.php
tests/src/ExistingSiteJavascript/MaintenancePageTest.php

ACMS-000: Fixes failing PHPUnit tests

---

composer.json
composer.lock
modules/acquia_cms_article/config/optional/core.entity_form_display.node.article.default.yml
modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/tests/src/ExistingSite/ContentTypeListTestBase.php
modules/acquia_cms_event/config/optional/core.entity_form_display.node.event.default.yml
modules/acquia_cms_page/config/optional/core.entity_form_display.node.page.default.yml
modules/acquia_cms_person/config/optional/core.entity_form_display.node.person.default.yml
modules/acquia_cms_place/config/optional/core.entity_form_display.node.place.default.yml
modules/acquia_cms_search/tests/src/Kernel/AcquiaFacetFacadeTest.php
modules/acquia_cms_site_studio/acquia_cms_site_studio.install
tests/src/ExistingSite/LoginRedirectionTest.php

**Motivation**
Fixes #ACMS-1592
Update test to use CKEditor5
NA

ACMS-1592: updated test to move from CKEditor to CKEditor5.

---

composer.json
composer.lock
tests/src/ExistingSite/DecoupledTest.php
tests/src/ExistingSiteJavascript/ContactInformationCardComponentTest.php
tests/src/ExistingSiteJavascript/ContainerTest.php
tests/src/ExistingSiteJavascript/LinkedFeatureCardComponentTest.php
tests/src/ExistingSiteJavascript/LogoCardComponentTest.php
tests/src/ExistingSiteJavascript/SearchTest.php

**Motivation**
Fixes #ACMS-1584
Fix tests/src failing tests
NA
Execute tests and verify all tests passing.

ACMS-1584: ACMS D10 Regression testing - Integrated ExistingSite PHPunit tests under tests/src directory.

---

modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_headless/composer.json
modules/acquia_cms_headless/src/Plugin/AcquiaCmsHeadless/HeadlessApiKeys.php
modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php

**Motivation**
Fixes ACMS-1498
Adding client id for headless

ACMS-1498: Fixing missing client id for headless.

---

modules/acquia_cms_common/composer.json

**Motivation**
Fixes #ACMS-1603 
Removed profile switch core patch.
NA
- Checkout ACMS-1603-common branch `git checkout ACMS-1603-common`
- Execute `composer install`
- Verify that profile switch patch does not present and getting applied

ACMS-1603: Removed profile switch core patch.

---

tests/src/ExistingSite/InstallStateTest.php

**Motivation**
- Fix failing CI job.
- Updated failing PHPUnit tests after removal of tour dashboard page.
N/A
PHPUnit tests should pass.

ACMS-1461: Updated PHPUnit tests after removal of tour dashboard page.

---

modules/acquia_cms_audio/acquia_cms_audio.info.yml
modules/acquia_cms_audio/acquia_cms_audio.install
modules/acquia_cms_audio/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTest.php
modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_common/config/optional/editor.editor.filtered_html.yml
modules/acquia_cms_common/config/optional/editor.editor.full_html.yml
modules/acquia_cms_common/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTest.php
modules/acquia_cms_common/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTestBase.php
modules/acquia_cms_document/acquia_cms_document.info.yml
modules/acquia_cms_document/acquia_cms_document.install
modules/acquia_cms_document/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTest.php
modules/acquia_cms_image/acquia_cms_image.info.yml
modules/acquia_cms_image/acquia_cms_image.install
modules/acquia_cms_page/acquia_cms_page.info.yml
modules/acquia_cms_place/acquia_cms_place.info.yml
modules/acquia_cms_video/acquia_cms_video.info.yml
modules/acquia_cms_video/acquia_cms_video.install
modules/acquia_cms_video/tests/src/FunctionalJavascript/Ckeditor5ConfigurationTest.php

**Motivation**
Fixes ACMS-1599

ACMS-1599: updated media library dependency for media model

---

modules/acquia_cms_tour/acquia_cms_tour.install

**Motivation**
Fixes ACMS-1461
Update hook for removed permission.

ACMS-1461: Remove permissions update hook.

---

modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_dam/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_headless/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
Fixes #ACMS-1627
Drupal 10 compatibility release.
NA

ACMS-1627: Drupal 10 compatible release.

---

modules/acquia_cms_tour/acquia_cms_tour.install

**Motivation**
Fixes ACMS-1461

ACMS-1461: Adding missing use statement.

---

modules/acquia_cms_headless/src/Plugin/AcquiaCmsHeadless/HeadlessNextEntityTypes.php

**Motivation**
Fixes ACMS-1601

ACMS-1601: Fixing next entity type on dashboard page.

---

modules/acquia_cms_common/acquia_cms_common.install

**Motivation**
Fixes #[ACMS-1600](https://backlog.acquia.com/browse/ACMS-1600)

ACMS-1600: Purge Errors.

---

modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/modules/acquia_cms_development/acquia_cms_development.install
modules/acquia_cms_common/src/EventSubscriber/ConfigEventsSubscriber.php
modules/acquia_cms_dam/acquia_cms_dam.module
modules/acquia_cms_headless/acquia_cms_headless.install
modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.install
modules/acquia_cms_page/acquia_cms_page.install
modules/acquia_cms_search/acquia_cms_search.install
modules/acquia_cms_search/acquia_cms_search.module
modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_site_studio/acquia_cms_site_studio.module
modules/acquia_cms_starter/acquia_cms_starter.install
modules/acquia_cms_tour/acquia_cms_tour.module
tests/src/ExistingSite/IntegratedPermissionsTest.php

**Motivation**
Fixes ACMS-1609

ACMS-1609: Adding is_syncing for hook_install, hook_modules_installed.

---

.github/workflows/acquia_cms_ci.workflow.yml

**Motivation**
Use latest release for ORCA.
Unpinned the ORCA version to always use latest release for ORCA.
N/A.
CI should pass

ORCA-505: Use latest release for ORCA.

---

modules/acquia_cms_headless/tests/src/Functional/DashboardApiKeysTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardBrowserTestBase.php
modules/acquia_cms_headless/tests/src/Functional/DashboardWebDriverTestBase.php
modules/acquia_cms_headless/tests/src/Traits/DashboardSectionTrait.php
modules/acquia_cms_headless/tests/src/Traits/DashboardTableTrait.php

**Motivation**
Fixes #ACMS-1642 ACMS-1493
Testcase coverage for API keys
NA
follow from ticket.

ACMS-1642: PHPUnit testcases for API Dashboard - API keys

---

.github/workflows/acquia_cms_ci.workflow.yml

ACMS-1493: Enable headless isolated test coverage in CI.

---

modules/acquia_cms_headless/tests/src/Functional/DashboardApiKeysTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUsersTest.php
modules/acquia_cms_headless/tests/src/Traits/DashboardSectionTrait.php

**Motivation**
Fixes #ACMS-1491
Headless API Dashboard - API Users testcase coverage.
NA
use from ticket

ACMS-1491: PHPUnit testcases for API Dashboard - API Users.

---

modules/acquia_cms_headless/tests/src/Functional/DashboardApiDocumentTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUrlTest.php

**Motivation**
Fixes ACMS-1490
PHPUnit testcases for API Dashboard - API Endpoints

ACMS-1490: PHPUnit testcases for API Dashboard - API Endpoints

---

modules/acquia_cms_audio/config/pack_acquia_cms_audio/cohesion_elements.cohesion_component.cpt_audio.yml
modules/acquia_cms_audio/config/pack_acquia_cms_audio/cohesion_sync.cohesion_sync_package.pack_acquia_cms_audio.yml
modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_site_studio/config/pack_acquia_cms_core/cohesion_sync.cohesion_sync_package.pack_acquia_cms_core.yml
modules/acquia_cms_site_studio/config/site_studio/site_studio.packages.yml
modules/acquia_cms_video/config/pack_acquia_cms_video/cohesion_elements.cohesion_component.cpt_video_media.yml
modules/acquia_cms_video/config/pack_acquia_cms_video/cohesion_sync.cohesion_sync_package.pack_acquia_cms_video.yml

**Motivation**
Fixes ACMS-1428
Update site studio components for audio and video.
Placing audio and video components under layout canvas

ACMS-1428: Adding audio package support for site studio.

---

composer.json
composer.lock

ACMS-000: Removed cohesion patch included in 7.0.1

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock
modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_common/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_dam/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_headless/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json
tests/ci/install.sh
tests/packages_alter.yml

**Motivation**
Removed composer-merge-plugin.
- The composer-merge-plugin is removed.
- Used local path repository.
N/A
- CI should pass.

ACMS-000: Remove composer-merge-plugin & use local path repository.

---

composer.lock
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_site_studio/modules/acquia_cms_site_studio_cm/src/Commands/ConfigImportExportCommands.php

ACMS-1239: Fix scaffolding name and some refactor.

---

modules/acquia_cms_common/src/RedirectHandler.php
tests/src/ExistingSite/LoginRedirectionTest.php

**Motivation**
Fixes ACMS-1510

ACMS-1510: Fixing the redirection issue with TFA module.

---

modules/acquia_cms_headless/tests/src/Functional/DashboardApiDocumentTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiKeysTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUrlTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUsersTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardNextjsSitesTest.php
modules/acquia_cms_headless/tests/src/Functional/HeadlessTestBase.php
modules/acquia_cms_headless/tests/src/Traits/DashboardSectionTrait.php

**Motivation**
Fixes #ACMS-1492
Testcase coverage for API keys
NA
follow from ticket.

ACMS-1492: PHPUnit testcases coverage for API Dashboard - Next.js Sites.

---

modules/acquia_cms_headless/tests/src/Functional/HeadlessFrontpageTest.php

**Motivation**
Fixes ACMS-1480
refactored headless test

ACMS-1480: Refactored headless test with Dashboard test base.

---

modules/acquia_cms_headless/tests/src/Functional/DashboardApiKeysTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUsersTest.php
modules/acquia_cms_headless/tests/src/Functional/SitePreviewTest.php

**Motivation**
Fixes ACMs-1484
Content preview test case

ACMS-1484: Content preview headless test case.

---

.github/dependabot.yml
composer.json
modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_common/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_dam/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_headless/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
Fixes #[ACMS-1518](https://backlog.acquia.com/browse/ACMS-1518)

ACMS-1518: Managing Dependabot updates for Acquia CMS 1.x, 2.x & develop

---

.github/dependabot.yml
modules/acquia_cms_common/composer.json

ACMS-1518: Update dependabot config.

---

composer.json
composer.lock
tests/integrated_tests_packages.yml
tests/packages_alter.yml

**Motivation**
ACMS-1661: Remove 'php-http/discovery' plugin from root composer.json
Update package dependencies.
N/A.
CI Should pass.

ACMS-1661: Upgrade 'php-http/discovery' plugin.

---

acquia_cms.profile
composer.json
composer.lock
tests/packages_alter.yml

ACMS-1661: Include plugin: 'php-http/discovery'.

ACMS-1661: Include plugin: 'php-http/discovery'.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes #ACMS-1662
Update responseve_preview to latest.

ACMS-1662: Update responsive_preview to latest.

---

modules/acquia_cms_headless/README.md
modules/acquia_cms_headless/tests/src/Functional/DashboardApiDocumentTest.php

**Motivation**
Fixes #ACMS-1422
Updated Readme for swagger-api/swagger-ui library, added testcase coverage.
NA

ACMS-1422: Fix Explore with Swagger UI headless issue.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes #ACMS-1664
Update config_ignore to beta from dev#commit
NA

ACMS-1664: Upgrade Config Ignore module version from dev to beta.

---

modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.module

**Motivation**
Fixes #ACMS-1448
Fixes headless menu discrepancies.

ACMS-1448: Headless CMS Administration Menu discrepancies.

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes #ACMS-1668
Module release
NA

ACMS-1668: modules release.

---

modules/acquia_cms_headless/tests/src/Functional/PureHeadlessModeMenuTest.php

**Motivation**
Fixes #ACMS-1481
PHPUnit testcase coverage for API Menu Items.
NA

ACMS-1481: PHPUnit testcase coverage for API Menu Items.

---

modules/acquia_cms_headless/tests/src/Functional/HeadlessModeEnablementTest.php

**Motivation**
Fixes #ACMS-1495
PHPunit  test coverage for headless mode enablement

ACMS-1495: PHPUnit testcases for Headless mode enablement.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml

**Motivation**
Fixes #ACMS-1573
Display log installation information in CI.
No

ACMS-1573: Add logic to display log installation information in CI.

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_site_studio/config/rewrite/filter.format.filtered_html.yml
modules/acquia_cms_site_studio/tests/src/Functional/FilterFormatFilteredHtmlTest.php

**Motivation**
Fixes #[ACMS-1655](https://backlog.acquia.com/browse/ACMS-1655)

ACMS-1655: Unable to run blt setup. Config rewrite issue.

---

modules/acquia_cms_page/acquia_cms_page.install
modules/acquia_cms_page/acquia_cms_page.post_update.php

ACMS-1665: Site Studio recommended translation configurations for existing customers.

---

modules/acquia_cms_common/src/RedirectHandler.php
modules/acquia_cms_common/tests/src/Functional/UserLoginFloodTest.php
tests/src/ExistingSite/LoginRedirectionTest.php

**Motivation**
Fixes ACMS-1519

ACMS-1519: Fixing failed user login.

---

composer.json
composer.lock

ACMS-000: Update Drupal Core to 10.0.4 & updated failing patch.

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.module

**Motivation**
Fixes #ACMS-1680
Fix entity browser modal not closing.
NA

ACMS-1680: Fix entity browser modal not closing.

---

modules/acquia_cms_tour/src/Services/StarterKitService.php

**Motivation**
Fixes #ACMS-1535
Import site studio package while starterkit setup via UI.
NA
Use from ticket.

ACMS-1535: Import site studio package while starterkit setup via UI.

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.module

**Motivation**
Fixes ACMS-1437
Added missed callable method.

ACMS-1437: Updating on callable method.

---

composer.lock
modules/acquia_cms_article/acquia_cms_article.info.yml
modules/acquia_cms_audio/acquia_cms_audio.info.yml
modules/acquia_cms_audio/composer.json
modules/acquia_cms_common/composer.json
modules/acquia_cms_component/acquia_cms_component.info.yml
modules/acquia_cms_component/composer.json
modules/acquia_cms_dam/acquia_cms_dam.info.yml
modules/acquia_cms_document/acquia_cms_document.info.yml
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/acquia_cms_event.info.yml
modules/acquia_cms_headless/acquia_cms_headless.info.yml
modules/acquia_cms_image/acquia_cms_image.info.yml
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/acquia_cms_page.info.yml
modules/acquia_cms_person/acquia_cms_person.info.yml
modules/acquia_cms_place/acquia_cms_place.info.yml
modules/acquia_cms_search/acquia_cms_search.info.yml
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/acquia_cms_starter.info.yml
modules/acquia_cms_toolbar/acquia_cms_toolbar.info.yml
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/acquia_cms_tour.info.yml
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/acquia_cms_video.info.yml
modules/acquia_cms_video/composer.json
scripts/deploy_code.sh

**Motivation**
Fixes #ACMS-1657
Update all modules to support common 1.7 & 2.0
NA

ACMS-1657: Provide support for oldest Drupal Core to all Acquia CMS modules.

---

modules/acquia_cms_audio/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
Fixes #ACMS-1657
Release 1.8.0
NA

ACMS-1657: release 1.8.0

---

.github/workflows/acquia_cms_ci.workflow.yml
tests/ci/before_install.blt.sh
tests/ci/run_update_hooks.sh
tests/ci/script.sh

**Motivation**
Fixes #ACMS-1401
CI to test modules upgrade on PR

ACMS-1401: CI to test modules upgrade on PR.

---

modules/acquia_cms_headless/tests/src/Functional/HeadlessDrushCommandsTest.php

**Motivation**
Fixes ACMS-1483
New test case for headless drush commands.

ACMS-1483: Headless drush command test.

---

composer.json
composer.lock

**Motivation**
Upgrade Drupal Core to 10.0.7.
The composer.lock updated to Drupal Core 10.0.5.
NA
CI should pass.

ACMS-1489: Upgrade Drupal Core to 10.0.7 and remove core patch.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock

**Motivation**
Fixes #ACMS-1690
Enable Drupal-Check in CI.
NA
Verify Drupal-Check give error if any else passing in CI

ACMS-1690: Enable Drupal-Check in CI.

---

composer.lock

**Motivation**
Fixes #NNN
Revert update done in ACMS-1707 for dependencies.

ACMS-1707: Revert dependencies back with php 8.1.

---

composer.lock
modules/acquia_cms_site_studio/composer.json

ACMS-1505: add conflicts in site studio.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes ACMS-1722
Removing the patches.

ACMS-1722: Checklistapi patche 1 causing error on form save.

---

composer.json
composer.lock
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
tests/src/ExistingSiteJavascript/CohesionComponentTestBase.php
tests/src/ExistingSiteJavascript/CohesionHelperTestBase.php
tests/src/ExistingSiteJavascript/CohesionTestBase.php
tests/src/ExistingSiteJavascript/ContactInformationCardComponentTest.php
tests/src/ExistingSiteJavascript/ContainerTest.php
tests/src/ExistingSiteJavascript/LinkedFeatureCardComponentTest.php
tests/src/ExistingSiteJavascript/LogoCardComponentTest.php

**Motivation**
Fixes #ACMS-1618
Update Site Studio existing site javascript test as per ACO-2372.
NA
Existing Site test should pass in CI.

ACMS-1618: Update Site Studio tests as per ACO-2372.

---

modules/acquia_cms_headless/tests/src/Functional/PureHeadlessModeMenuTest.php
modules/acquia_cms_site_studio/acquia_cms_site_studio.install
tests/src/ExistingSiteJavascript/CohesionTestBase.php

ACMS-1739: Save entity conditionally

---

modules/acquia_cms_common/acquia_cms_common.services.yml
modules/acquia_cms_common/src/Services/ToggleModulesService.php

**Motivation**
Fixes #ACMS-1746
Update toggle module service.
NA

ACMS-1746: update toggle module service with dependency injection.

---

composer.json

**Motivation**
Fixes #ACMS-1746
removed pinned acquia_search version and add library in CI.
NA

ACMS-1746: removed pinned acquia_search version.

---

modules/acquia_cms_headless/tests/src/Functional/DashboardApiDocumentTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiKeysTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUrlTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUsersTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardNextjsSitesTest.php
modules/acquia_cms_headless/tests/src/Functional/HeadlessContentTest.php
modules/acquia_cms_headless/tests/src/Traits/DashboardSectionTrait.php

**Motivation**
Fixes ACMS-1724
Use of scope variable for element failure.

ACMS-1724: Fix element not interactable Issue in CI with headless tests.

---

composer.json

**Motivation**
Fixes #ACMS-1833
Provide support for Drush 12 in Acquia CMS.
NA
Follow from ticket ACMS-1833

ACMS-1833: Provide support for Drush 12 in Acquia CMS.

---

composer.lock
modules/acquia_cms_audio/config/pack_acquia_cms_audio/cohesion_elements.cohesion_component.cpt_audio.yml
tests/ci/install.sh
tests/src/ExistingSiteJavascript/AudioComponentTest.php

**Motivation**
Fixes #ACMS-1646
Audio media integration with soundcloud and site studio.
NA

ACMS-1646: Audio media integration with soundcloud and site studio.

---

modules/acquia_cms_common/src/EventSubscriber/HttpsRedirectSubscriber.php

**Motivation**
Fixes #ACMS-1850
fix enable enforced HTTPS redirects causes infinite loop
NA

ACMS-1850: fix enable enforced HTTPS redirects causes infinite loop

---

composer.lock
modules/acquia_cms_common/src/Commands/AcmsCommands.php
modules/acquia_cms_common/src/Services/ConfigImporterService.php
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes ACMS-1853

ACMS-1853: Adding symfony/contracts for eventDispatcher.

---

composer.lock

ACMS-1727: Update lock with correct dependency.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock
modules/acquia_cms_article/tests/src/Functional/ArticleTest.php
modules/acquia_cms_common/composer.json
modules/acquia_cms_event/tests/src/Functional/EventTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardNextjsSitesTest.php
modules/acquia_cms_headless/tests/src/Functional/HeadlessModeEnablementTest.php
modules/acquia_cms_page/tests/src/Functional/PageTest.php
modules/acquia_cms_person/tests/src/Functional/PersonTest.php
modules/acquia_cms_place/tests/src/Functional/PlaceTest.php
modules/acquia_cms_search/composer.json

**Motivation**
Fixes ACMS-1821
Checking compatiblity for php8.2

ACMS-1821: Initial commit for php 8.2 compatible.

---

modules/acquia_cms_common/acquia_cms_common.install

**Motivation**
An update hook added to update the config_ignore.settings file.
The `hook_update_N()` added in acquia_cms_common module.
N/A
- Module upgrades CI should pass.
- Manual Testing.

ACMS-000: An update hook added to update the config_ignore.settings file.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/modules/acquia_cms_support/src/Service/AcquiaCmsConfigSyncService.php
modules/acquia_cms_common/src/Commands/AcmsCommands.php
modules/acquia_cms_common/src/Services/ConfigImporterService.php
modules/acquia_cms_event/tests/src/Unit/DefaultContentUpdateEventTest.php
tests/src/ExistingSite/InstallStateTest.php

**Motivation**
Fixes #ACMS-1861
Fix Drupal Check notices for Drupal 10.1
NA
Check CI(drupal-check), it should pass.

ACMS-1861: Fix Drupal Check notices for Drupal 10.1

---

composer.json
composer.lock

**Motivation**
Fixes #ACMS-1858
Remove checklist api patch as it's released with latest version.
NA
- CI should pass.

ACMS-1858: Remove checklistapi patch as released with latest version.

---

composer.json
composer.lock
modules/acquia_cms_common/tests/src/FunctionalJavascript/MediaEmbedTestBase.php

**Motivation**
Fixes #ACMS-1858
Fix media test failure in Acquia CMS modules.
NA
**Note:** 
Please review only [this](https://github.com/acquia/acquia_cms/pull/1583/commits/10ba2224333cd9623539e227c41ee13672c5a56d) commit.

ACMS-1858: Fix media test failure in Acquia CMS modules.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_headless/composer.json
modules/acquia_cms_search/composer.json

**Motivation**
Fixes #[ACMS-1867](https://backlog.acquia.com/browse/ACMS-1867)

ACMS-1867: Release PHP 8.2 compatible ACMS.

---

modules/sitestudio_config_management/CONTRIBUTING.md
modules/sitestudio_config_management/README.md
modules/sitestudio_config_management/tests/src/Kernel/ConfigurationTest.php
modules/sitestudio_config_management/tests/src/Kernel/DrushCommandTraitTest.php
modules/sitestudio_config_management/tests/src/Kernel/SiteStudioConfigServiceTest.php

**Motivation**
Fixes #ACMS-1866
Readme updated, fixed phpcs notices.
NA
Verify Readme file.

ACMS-1866: Update sitestudio config management readme with config path and phpcs notice.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.lock
modules/acquia_cms_common/src/EventSubscriber/ConfigEventsSubscriber.php
modules/acquia_cms_common/src/EventSubscriber/HttpsRedirectSubscriber.php
modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaCmsTelemetry.php
modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/EventSubscriber/ConfigSubscriber.php
modules/acquia_cms_image/src/Config/AcquiaCmsImageConfigSubscriber.php
modules/acquia_cms_search/tests/src/FunctionalJavascript/AcquiaFacetSearchTest.php
modules/acquia_cms_search/tests/src/Kernel/AcquiaFacetFacadeTest.php
modules/acquia_cms_starter/src/EventSubscriber/DefaultContentEventUpdateSubscriber.php
modules/sitestudio_config_management/src/Config/ConfigImportEventSubscriber.php
tests/src/ExistingSiteJavascript/CohesionTestBase.php

**Motivation**
Fixes ACMS-1862

ACMS-1862: Tests deprecation fixes with D10.1

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes #[ACMS-1727](https://backlog.acquia.com/browse/ACMS-1727)

ACMS-1727: Field UI improvements.

---

modules/acquia_cms_article/acquia_cms_article.install
modules/acquia_cms_event/acquia_cms_event.install
modules/acquia_cms_image/acquia_cms_image.install
modules/acquia_cms_page/acquia_cms_page.install
modules/acquia_cms_person/acquia_cms_person.install
modules/acquia_cms_place/acquia_cms_place.install
modules/acquia_cms_search/acquia_cms_search.install
modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_video/acquia_cms_video.install

**Motivation**
Fixes #[ACMS-1863](https://backlog.acquia.com/browse/ACMS-1863)
Add additional check.
NA

ACMS-1863: Fix upgrade issues resulting in partial entities.

---

acms/build.yml
acquia-pipelines.yml
composer.json
composer.lock
hooks/common/post-code-deploy/install_acms.sh
hooks/common/post-code-update/install_acms.sh
hooks/common/post-db-copy/toggle_modules.sh

**Motivation**
Fixes #[ACMS-1907]

ACMS-1907: Update deployment scrip for acquia_cms.

---

acms/build.yml
composer.json
composer.lock
modules/acquia_cms_common/tests/src/Functional/UserLoginFloodTest.php
tests/ci/install.sh
tests/src/ExistingSiteJavascript/AudioComponentTest.php

ACMS-000: Update dependencies to the latest.

---

acquia_cms.install

**Motivation**
Fixes #ACMS-1905
Track Acquia CMS Starterkits in telemetry data.
NA

ACMS-1905: Track Acquia CMS starterkits in telemetry data.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml
tests/cypress/cypress.config.js
tests/cypress/cypress/e2e/specsACMS/acms.content.spec.js
tests/cypress/cypress/pages/AdminToolBar.js
tests/cypress/cypress/pages/Article.js
tests/cypress/cypress/pages/Content.js
tests/cypress/cypress/pages/Event.js
tests/cypress/cypress/pages/Extend.js
tests/cypress/cypress/pages/Page.js
tests/cypress/cypress/pages/PasswordPolicy.js
tests/cypress/cypress/pages/Person.js
tests/cypress/cypress/pages/Place.js
tests/cypress/cypress/pages/Taxonomy.js
tests/cypress/cypress/pages/TestData.js
tests/cypress/cypress/pages/ToolBar.js
tests/cypress/cypress/pages/TourPage.js
tests/cypress/cypress/pages/UserRoles.js
tests/cypress/cypress/pages/Utility.js
tests/cypress/cypress/support/commands.js
tests/cypress/cypress/support/e2e.js
tests/cypress/package-lock.json
tests/cypress/package.json

**Motivation**
Fixes #ACMS-1901
Optimize Cypress tests.
NA

ACMS-1901: Optimize Cypress tests.

---

modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaCmsTelemetry.php

**Motivation**
Fixes ACMS-1386
Added installTime for telemetry data.

ACMS-1386: Include install time of site setup.

---

.github/workflows/acquia_cms_cron.yml

ACMS-000: Add variable CONNECTOR_KEY in cron CI jobs.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml

**Motivation**
Fixes #ACMS-1930
Remove failing patch.
NA
Verify install task not failing in Cron.

ACMS-1930: remove failing patch from cron.

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_site_studio/composer.json
modules/sitestudio_config_management/composer.json

**Motivation**
Fixes ACMS-1909
sitestudio_config_management dependency in acquia_cms_site_studio.

ACMS-1909: Adding dependency of sitestudio_config_management to acquia_cms_site_studio module.

---

acquia_cms.profile
composer.json
src/Commands/SiteInstallCommands.php

**Motivation**
Fixes #ACMS-1932
Capture and send Acquia Sites data to telemetry.
NA

ACMS-1932: Capture and send Acquia Sites data to telemetry.

---

tests/src/ExistingSiteJavascript/SearchTest.php

**Motivation**
Fixes #[ACMS-1930](https://backlog.acquia.com/browse/ACMS-1930)
Fix failing search test.
NA

ACMS-1930: Fix failing search test in integrated_existing_site_tests job.

---

composer.json

**Motivation**
Fixes #ACMS-1940
ACMS 1.5.6 release changes
NA

ACMS-1940: Acquia CMS 1.5.6 release.

---

modules/sitestudio_config_management/src/Commands/PostConfigImportHook.php
modules/sitestudio_config_management/src/Config/ConfigImportEventSubscriber.php

**Motivation**
Fixes #[ACMS-1937](https://backlog.acquia.com/browse/ACMS-1937)
Update sitestudio_config_management module to work with custom profile.
NA

ACMS-1937: Update sitestudio_config_management module to work with custom profile.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
For users with limited permissions (i.e. content editors), many menu items irrelevant to the role still appear in the toolbar. This can be overwhelming so empty top level menu items should have restricted access and not be shown if the user lacks the permission for it.
This is a known problem where an unnecessarily complicated interface needs to be explained/simplified to newer users.
Fixes #[ACMS-1920](https://backlog.acquia.com/browse/ACMS-1920)
The current approach is to add a route parameter to several routes. Then add an access check for routes that have the new parameter. The access check loads the corresponding menu link and its children. If the user does not have access to any of the children, then deny access to the page. If any of the children …

ACMS-1920: Hide administration menu links that do not have visible child links

---

modules/acquia_cms_common/modules/acquia_cms_support/src/Service/AcquiaCmsConfigSyncService.php

**Motivation**
Fixes ACMS-1868
Fixing the deprecation for diff and nclosing method.

ACMS-1868: Updating the logic for deprecated method diff and nclosing.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes ACMS-1914
Removed previous UI improvement patch and include new patch for combined field storage form instances with UI fields.

ACMS-1914: Combined field storage and instance forms.

---

.github/workflows/acquia_cms_ci.workflow.yml

**Motivation**
This adds Google API related credentials to enable Domo Integration.

ORCA-557: Enable Domo integration

---

README.md

**Motivation**
Redirect the developers at correct link
URL change

corrected the link

---

modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_common/src/Services/AcmsUtilityService.php
modules/acquia_cms_common/templates/status-report-general-info-starter-kit.html.twig

**Motivation**
Fixes #ACMS-1985(https://acquia.atlassian.net/browse/ACMS-1985)

ACMS-1985: Display Starter Kit name in status report page.

---

modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaCmsTelemetry.php

**Motivation**
Fixes ACMS-1997
Adding user_id key along with ACMS data for sumologic

ACMS-1997: Adding user id with ACMS data for sumologic.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml
composer.json
composer.lock
modules/acquia_cms_common/composer.json
tests/src/ExistingSiteJavascript/GoogleMapComponentTest.php

**Motivation**
Fixes ACMS-3340
Adding patch for supporting D9 in ORCA.

ACMS-3340: Drupal 9 supports patch in ORCA.

---

composer.lock
modules/acquia_cms_headless/composer.json

**Motivation**
Fixes #[ACMS-3279](https://acquia.atlassian.net/browse/ACMS-3279)
Update openapi_ui_swagger to latest 1.0 stable release.
NA
follow from ticket.

ACMS-3279: Update openapi_ui_swagger to stable release.

---

modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaCmsTelemetry.php
modules/acquia_cms_common/tests/src/Kernel/AcquiaCmsTelemetryTest.php
modules/acquia_cms_tour/src/Plugin/AcquiaCmsStarterKit/StarterKitConfigForm.php

ACMS-1976: Add new installation variable in telemetry data to identify new sites.

---

composer.lock
modules/acquia_cms_search/composer.json
tests/src/ExistingSiteJavascript/SearchBlockTest.php
tests/src/ExistingSiteJavascript/SearchTest.php

**Motivation**
Fixes #[ACMS-3428](https://acquia.atlassian.net/jira/software/c/projects/ACMS/boards/1295?selectedIssue=ACMS-3428&sprints=8619)
Pin and patch facets_pretty_paths module.
Pin facets_pretty_paths 1.4.0

ACMS-3428: Search block action is missing with facets_pretty_paths 1.5.0

---

acms-run-tests.sh
composer.lock
modules/acquia_cms_site_studio/composer.json
modules/sitestudio_config_management/composer.json
tests/ci/install.sh
tests/src/ExistingSiteJavascript/AudioComponentTest.php
tests/src/ExistingSiteJavascript/SearchBlockTest.php

**Motivation**
Fixes [ACMS-3407](https://acquia.atlassian.net/browse/ACMS-3407)

ACMS-3407: Validate feature/site-studio-7.4.x changes with stable release.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes ACMS-3434
Added pin version for workbench_email with a patch

ACMS-3434: Workbench email pinned version with patch.

---

modules/acquia_cms_image/config/pack_acquia_cms_image_core/cohesion_elements.cohesion_component.cpt_hero.yml
modules/acquia_cms_site_studio/config/pack_acquia_cms_core/cohesion_elements.cohesion_component.cpt_heading.yml
modules/acquia_cms_site_studio/config/pack_acquia_cms_core/cohesion_elements.cohesion_component.cpt_linked_feature_card.yml

**Motivation**
Fixes #[ACMS-3350](https://acquia.atlassian.net/browse/ACMS-3350)
Update UI kit(s) with patched components for in-place editing.
NA

ACMS-3350: Update components for in-place editing.

---

composer.lock
modules/acquia_cms_search/composer.json

**Motivation**
Fixes #ACMS-3395

ACMS-3395: Update Search API dependency to 8.x-1.31.

---

modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/acquia_cms_common.module

**Motivation**
Fixes ACMS-3474
Moved out smart_trim and moderation_sidebar from .info.yml file

ACMS-3474: Move specific modules from info.yml to .install file.

---

composer.lock
modules/acquia_cms_common/acquia_cms_common.services.yml
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaCmsTelemetry.php
modules/acquia_cms_common/tests/src/Kernel/AcquiaCmsTelemetryTest.php

ACMS-3416: Remove amplitude log request from ACMS Common module.

---

.github/workflows/acquia_cms_cron.yml

**Motivation**
Fixes #ACMS-3471
Fixes acquia_cms_cron job

ACMS-3471: Fix Integrated test cases failure in cron Job.

---

modules/acquia_cms_toolbar/acquia_cms_toolbar.module
modules/acquia_cms_toolbar/js/acms_toolbar.js

**Motivation**
Fixes #[ACMS-3406](https://acquia.atlassian.net/browse/ACMS-3406)
Update toolbar to work with any admin theme.
NA

ACMS-3406: Update ACMS toolbar js.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml
composer.lock
modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/composer.json

ACMS-3473: update Page title should contextualize the local navigation patch as per drupal core latest release.

---

.github/workflows/acquia_cms_ci.workflow.yml

ACMS-3473: update CI with drupal 10.1.8 patch.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes #[ACMS-3442](https://acquia.atlassian.net/browse/ACMS-3442)
Update workbench_email to latests release 3.0.3 version.
NA
follow from ticket.

ACMS-3442: Update workbench_email to latests release 3.0.3 version.

---

composer.lock

**Motivation**
Fixes https://github.com/acquia/acquia_cms/actions/runs/7710844330/job/21015022969

ACMS-000: Update dependencies as per php 8.1.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes ACMS-3538
Updating workbench_email to ^3.0

ACMS-3538: Updating workbench email version.

---

.github/workflows/security-outdated-check.yml

Changed V3 to V4

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml

ACMS-000: Update github workflow to run CI on PHP 8.3.

---

.github/workflows/acquia_cms_cron.yml
tests/ci/install.sh

ACMS-3442: Allow Automation with modules development branch.

---

composer.lock
modules/acquia_cms_article/composer.json
modules/acquia_cms_audio/composer.json
modules/acquia_cms_common/composer.json
modules/acquia_cms_component/composer.json
modules/acquia_cms_dam/composer.json
modules/acquia_cms_document/composer.json
modules/acquia_cms_event/composer.json
modules/acquia_cms_headless/composer.json
modules/acquia_cms_image/composer.json
modules/acquia_cms_page/composer.json
modules/acquia_cms_person/composer.json
modules/acquia_cms_place/composer.json
modules/acquia_cms_search/composer.json
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_starter/composer.json
modules/acquia_cms_toolbar/composer.json
modules/acquia_cms_tour/composer.json
modules/acquia_cms_video/composer.json

**Motivation**
Fixes #NNN
Added dev releases of acquia_cms_common module

ACMS-000: Use stable release for all acquia_cms modules.

---

gitlab_templates/.gitlab-ci.yml

**Motivation**
Fixes Generic gitlab template for ACMS modules
Generic gitlab template for ACMS modules

ACMS-0000: Generic gitlab template for ACMS modules.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes #ACMS-3581
Remove failing patch as merged in Drupal core 10.2.x version.

ACMS-3581: remove 3370946 patch as failing with Drupal core 10.2.x version.

---

modules/acquia_cms_common/tests/src/Functional/NodeBreadcrumbTest.php
modules/acquia_cms_image/tests/src/Functional/ImageFormatterTest.php
modules/acquia_cms_search/tests/src/FunctionalJavascript/AcquiaFacetSearchTest.php

**Motivation**
Fixes #ACMS-3581
Update testing theme to stark.

ACMS-3581: update testing theme to stark.

---

acms-run-tests.sh

ACMS-000: Update chromedriver download URL.

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/src/AcquiaCmsCommonServiceProvider.php
modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaConnectorTelemetryOverride.php

**Motivation**
Fixes #[ACMS-3417](https://acquia.atlassian.net/browse/ACMS-3417)
Update Acquia CMS telemetry as per Acquia Connector changes.
NA

ACMS-3417: Update Acquia CMS Telemetry as per Acquia Connector changes.

---

modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_site_studio/tests/src/ExistingSite/NodeRevisionDeleteConfigTest.php
modules/acquia_cms_site_studio/tests/src/Functional/SiteStudioCoreTest.php

ACMS-3628: Refactor test for site studio.

---

modules/acquia_cms_site_studio/.gitlab-ci.yml

**Motivation**
Fixes #[ACMS-3657](https://acquia.atlassian.net/browse/ACMS-3657)
Skip apply patch for latest EOL Major in CI.

ACMS-3657: Skip apply patch for latest EOL Major in CI.

---

composer.lock

**Motivation**
Fix composer vulnerability.
Update composer to ^2.7.0(latest version).
NA

ACMS-3660: Fix composer vulnerability.

---

modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_common/src/Services/AcmsUtilityService.php

**Motivation**
Fixes #[ACMS-1987](https://acquia.atlassian.net/browse/ACMS-1987)
Fix status report page issue starterkit name display.
NA

ACMS-1987: Fix status report page issue starterkit name display.

---

composer.lock
modules/acquia_cms_common/composer.json

**Motivation**
Fixes #ACMS-3623
Add Acquia Connector conflict(<4.0.6) in Acquia CMS Common module.
NA

ACMS-3623: Add Acquia Connector conflict in Acquia CMS Common module.

---

composer.json
composer.lock
modules/acquia_cms_site_studio/composer.json
modules/sitestudio_config_management/composer.json

**Motivation**
Fixes #[ACMS-3645](https://acquia.atlassian.net/browse/ACMS-3645)
Update Site Studio to 7.5.x version, and verify.
NA
**Note:**
The tests are failing because Starterkit is attempting to install and set Acquia Claro as the admin theme. Acquia Claro theme is replaced with GIN theme.

ACMS-3645: Update Site Studio to 7.5.x version.

---

composer.json
composer.lock

ACMS-000: Update lock with latest version.

---

.github/workflows/acquia_cms_ci.workflow.yml
tests/ci/script.sh

**Motivation**
Fixes #ACMS-3649
Patch orca to remove local setting in case of DRS.
NA

ACMS-3649: Patch orca to remove local setting in case of DRS.

---

composer.lock
modules/acquia_cms_search/composer.json

**Motivation**
Fixes #[ACMS-3537](https://acquia.atlassian.net/browse/ACMS-3537)
Support facets pretty paths major release 2.0.x version.
NA

ACMS-3537: Support facets pretty paths major release 2.0.x version.

---

composer.lock
modules/acquia_cms_search/composer.json

**Motivation**
Fixes #ACMS-3676
Includes new release of facets 2.0.7

ACMS-3676: Fix and include the latest release of facets module.

---

composer.lock
modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/composer.json

ACMS-3648: Add update hook to remove telemetry opted state variable.

---

composer.json
composer.lock
modules/acquia_cms_common/composer.json

ACMS-3560: Allow to use moderation_dashboard 2||3.

---

.github/workflows/acquia_cms_ci.workflow.yml

ACMS-3648: Allow module tests in CI.

---

DEVELOPING.md
README.md

**Motivation**
Fixes#ACMS-3502
Update DEVELOPING.md to include php memory limit should be 256M

ACMS-3502: Update DEVELOPING.md

---

modules/acquia_cms_search/composer.json

**Motivation**
Fixes #ACMS-3747

ACMS-3747: Unpin facets module.

---

composer.lock
modules/acquia_cms_image/composer.json

**Motivation**
Fixes #[ACMS-3952](https://acquia.atlassian.net/browse/ACMS-3952)
Remove Focal Point Patch from ACMS Image.
NA

ACMS-3952: Remove Focal Point Patch from ACMS Image.

---

modules/acquia_cms_common/modules/acquia_cms_support/tests/src/Functional/AcquiaCmsConfigSyncTest.php
modules/acquia_cms_common/tests/packages_alter.yml

**Motivation**
Fixes #[ACMS-3680](https://acquia.atlassian.net/browse/ACMS-3680)
Update ACMS Common to fix GitLab CI.
NA
Review CI.

ACMS-3680: Fix failing text with 10.3.x version.

---

modules/acquia_cms_person/config/optional/views.view.people.yml

ACMS-4015: Revert people view to default.

---

modules/acquia_cms_event/acquia_cms_event.info.yml

**Motivation**
Fixes #[ACMS-3923](https://acquia.atlassian.net/browse/ACMS-3923)
Drupal 11 compatibility fixes for ACMS Event.
NA

ACMS-3923: Drupal 11 compatibility fixes for ACMS Event.

---

modules/acquia_cms_place/acquia_cms_place.info.yml

**Motivation**
Fixes #[ACMS-3927](https://acquia.atlassian.net/browse/ACMS-3927)
Drupal 11 compatibility fixes for ACMS Place.
NA

ACMS-3927: Drupal 11 compatibility fixes for ACMS Place.

---

modules/acquia_cms_image/acquia_cms_image.info.yml

**Motivation**
Fixes #ACMS-3924
Drupal 11 compatibility fixes for ACMS Image.
NA

ACMS-3924: Drupal 11 compatibility fixes for ACMS Image.

---

modules/acquia_cms_page/acquia_cms_page.info.yml

**Motivation**
Fixes #ACMS-3926
Drupal 11 compatibility fixes for ACMS Person.
NA

ACMS-3925: Drupal 11 compatibility fixes for ACMS Page.

---

modules/acquia_cms_person/acquia_cms_person.info.yml

**Motivation**
Fixes #ACMS-3926
Drupal 11 compatibility fixes for ACMS Person.
NA

ACMS-3926: Drupal 11 compatibility fixes for ACMS Person.

---

modules/acquia_cms_audio/acquia_cms_audio.info.yml

**Motivation**
Fixes #ACMS-3919
Drupal 11 compatibility fixes for ACMS Audio.
NA

ACMS-3919: Drupal 11 compatibility fixes for ACMS Audio.

---

modules/acquia_cms_document/acquia_cms_document.info.yml

**Motivation**
Fixes #ACMS-3922
Drupal 11 compatibility fixes for ACMS Document.
NA

ACMS-3922: Drupal 11 compatibility fixes for ACMS Document.

---

modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/acquia_cms_common.module
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/modules/acquia_cms_development/acquia_cms_development.info.yml
modules/acquia_cms_common/modules/acquia_cms_support/acquia_cms_support.info.yml
modules/acquia_cms_common/modules/acquia_cms_support/src/Controller/AcquiaCmsConfigDiff.php
modules/acquia_cms_common/modules/acquia_cms_support/src/Service/AcquiaCmsConfigSyncService.php
modules/acquia_cms_common/modules/acquia_cms_support/tests/src/Functional/AcquiaCmsConfigSyncTest.php
modules/acquia_cms_common/src/Services/ConfigImporterService.php
modules/acquia_cms_common/tests/src/ExistingSite/ContentTypeListTestBase.php
modules/acquia_cms_common/tests/src/Functional/BasicPermissionsTest.php
modules/acquia_cms_common/tests/src/Functional/ContentPermissionsTestBase.php
modules/acquia_cms_common/tests/src/Functional/EntityPermissionsTestBase.php
modules/acquia_cms_common/tests/src/Functional/MediaPermissionsTestBase.php
modules/acquia_cms_common/tests/src/Traits/EntityPermissionsTrait.php
modules/acquia_cms_common/tests/src/Traits/PermissionsTrait.php
modules/acquia_cms_event/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_event/tests/src/ExistingSite/TabsBlockTest.php
modules/acquia_cms_page/tests/src/ExistingSite/TabsBlockTest.php
modules/acquia_cms_person/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_place/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_site_studio/tests/src/Functional/SiteStudioPermissionsTest.php
tests/src/ExistingSite/IntegratedPermissionsTest.php

**Motivation**
Fixes #ACMS-3920
Drupal 11 compatibility fixes for ACMS Common.
NA

ACMS-3920: Drupal 11 compatibility fixes for ACMS Common.

---

modules/acquia_cms_article/acquia_cms_article.info.yml
modules/acquia_cms_article/tests/src/ExistingSite/BreadcrumbTest.php
modules/acquia_cms_article/tests/src/ExistingSite/TabsBlockTest.php

**Motivation**
Fixes #ACMS-3918
Drupal 11 compatibility fixes for ACMS Article.
NA

ACMS-3918: Drupal 11 compatibility fixes for ACMS Article.

---

modules/acquia_cms_toolbar/css/acquia_cms_toolbar.css

**Motivation**
Fixes #ACMS-4056
Fix Acquia CMS toolbar styling breaks core off-canvas dialog rendering issue.
NA

ACMS-4056: Acquia CMS toolbar styling breaks core off-canvas dialog rendering fixes.

---

modules/acquia_cms_search/acquia_cms_search.info.yml

**Motivation**
Fixes #[ACMS-3928](https://acquia.atlassian.net/browse/ACMS-3928)
D11 upgrade Acquia CMS DAM
NA
Follow JIRA ticket testing steps

ACMS-3928: D11 upgrade Acquia CMS Search.

---

modules/acquia_cms_video/acquia_cms_video.info.yml

**Motivation**
Fixes #ACMS-3932
Drupal 11 compatibility fixes for ACMS Video.
NA

ACMS-3932: Drupal 11 compatibility fixes for ACMS Video.

---

modules/acquia_cms_tour/acquia_cms_tour.info.yml
modules/acquia_cms_tour/src/Plugin/AcquiaCmsStarterKit/StarterKitSelectionForm.php

**Motivation**
Fixes #ACMS-3931
Added Drupal 11 version.

ACMS-3931: Adding D11 version.

---

modules/acquia_cms_dam/acquia_cms_dam.info.yml

**Motivation**
Fixes #[ACMS-3921](https://acquia.atlassian.net/browse/ACMS-3921)
D11 upgrade Acquia CMS DAM
NA
Follow JIRA ticket testing steps

ACMS-3921: D11 upgrade Acquia CMS DAM.

---

modules/acquia_cms_toolbar/acquia_cms_toolbar.info.yml

**Motivation**
Fixes #ACMS-3930
Drupal 11 compatibility fixes for ACMS Toolbar.
NA

ACMS-3930: Drupal 11 compatibility fixes for ACMS Toolbar.

---

modules/acquia_cms_starter/acquia_cms_starter.info.yml
modules/acquia_cms_starter/modules/acquia_cms_site_studio_content/acquia_cms_site_studio_content.info.yml

**Motivation**
Fixes #[ACMS-4045](https://acquia.atlassian.net/browse/ACMS-4045)
Drupal 11 compatibility fixes for ACMS Starter.
NA

ACMS-4045: Drupal 11 compatibility fixes for ACMS Starter.

---

modules/acquia_cms_common/acquia_cms_common.install
modules/acquia_cms_common/config/optional/editor.editor.filtered_html.yml
modules/acquia_cms_common/config/optional/editor.editor.full_html.yml
modules/acquia_cms_common/modules/acquia_cms_support/tests/src/Functional/AcquiaCmsConfigSyncTest.php
modules/acquia_cms_common/src/Facade/ConfigHandlerFacade.php
modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_site_studio/config/optional/editor.editor.cohesion.yml

**Motivation**
Fixes ACMS-4081
Fixing schemas for editors as per CKEditor5.

ACMS-4081: Fixing schema for editors as per CKeditor5.

---

modules/acquia_cms_component/acquia_cms_component.info.yml
modules/acquia_cms_component/components/block/react_component_block/react_component_block.component.yml
modules/acquia_cms_component/components/block/react_component_block/react_component_block.twig
modules/acquia_cms_component/components/libraries/api_library/api_library.component.yml
modules/acquia_cms_component/components/libraries/api_library/api_library.twig
modules/acquia_cms_component/components/libraries/react_library/react_library.component.yml
modules/acquia_cms_component/components/libraries/react_library/react_library.twig

**Motivation**
Fixes #ACMS-4042(https://acquia.atlassian.net/browse/ACMS-4042)
NA
- Install site on Drupal 10.3
- enable acquia_cms_compoent and acquia_cms_article module
- Place react block with article CT
- Create some article content and verify that its appearing under the block

ACMS-4042: D11 upgrade Acquia CMS Component.

---

modules/acquia_cms_headless/acquia_cms_headless.info.yml
modules/acquia_cms_headless/composer.json
modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.info.yml
modules/acquia_cms_headless/tests/src/Functional/DashboardApiKeysTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardApiUsersTest.php
modules/acquia_cms_headless/tests/src/Functional/DashboardNextjsSitesTest.php
modules/acquia_cms_headless/tests/src/Functional/PureHeadlessModeMenuTest.php
modules/acquia_cms_headless/tests/src/Traits/DashboardTableTrait.php

**Motivation**
Fixes ACMS-4044
Supporting D11.

ACMS-4044: Initial changes for D11 Acquia cms headless.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock
modules/acquia_cms_common/acquia_cms_common.services.yml
modules/acquia_cms_common/src/Services/ConfigImporterService.php
modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
modules/acquia_cms_site_studio/composer.json

ACMS-3929: Drupal 11 compatibility fixes for ACMS SiteStudio.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml

**Motivation**
Update orca patches in workflow.

ACMS-4173: Update orca patches added in workflow.

---

modules/acquia_cms_headless/composer.json

**Motivation**
Fixes ACMS-4190
Adding conflict of subrequest.

ACMS-4190: Adding conflict of subrequest.

---

.github/workflows/acquia_cms_ci.workflow.yml
.github/workflows/acquia_cms_cron.yml
composer.json
composer.lock
modules/acquia_cms_dam/composer.json

ACMS-4173: Update Workflow as per Drupal 11 release.

---

.github/workflows/acquia_cms_ci.workflow.yml
modules/acquia_cms_site_studio/.gitlab-ci.yml
modules/acquia_cms_site_studio/.gitlab-ci/patches/patches.json
modules/acquia_cms_site_studio/tests/src/Functional/SiteStudioPermissionsTest.php

ACMS-4206: Fix site studio failing test.

---

README.md

Change Acquia CMS to Acquia Drupal Starter Kit
**Motivation**
Rebranding of Acquia CMS
Acquia CMS to Acquia Drupal Starter Kit

Announcement of Acquia Drupal Starter Kit

---

modules/acquia_cms_common/modules/acquia_cms_development/acquia_cms_development.install

**Motivation**
Fixes ACMS-4431
Check of cohesion module exists
Check of googleMapApiKeyForm class exists

ACMS-4431: Conditional check to handle the googleMapApiKeyForm existence.

---

composer.json
composer.lock
modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
modules/acquia_cms_site_studio/config/optional/editor.editor.cohesion.yml
modules/acquia_cms_site_studio/config/optional/filter.format.cohesion.yml

**Motivation**
Fixes [#ACMS-4430](https://acquia.atlassian.net/browse/ACMS-4430)
Fix Site Studio (Text formats and editors) as per CKEditor5.
NA

ACMS-4430: Fix Site Studio (Text formats and editors) as per CKEditor5.

---

composer.json
composer.lock

**Motivation**
Update Site Studio to latest D11 compatible version.
Site Studio to latest D11 compatible 8.0.3 version.
NA

ACMS-4237: Update Site Studio to latest D11 compatible version.

---

composer.json
composer.lock

Remove site studio D11 compatibility patch.

---

composer.lock
modules/acquia_cms_site_studio/composer.json
modules/acquia_cms_site_studio/src/Form/AcquiaCmsSiteStudioSiteConfigureForm.php

**Motivation**
ACMS-000
Validate site studio 8.1.x version in CI.
NA

ACMS-000: Update site studio to use 8.1.0 version.

---

modules/acquia_cms_site_studio/acquia_cms_site_studio.install
modules/acquia_cms_site_studio/acquia_cms_site_studio.module
modules/acquia_cms_site_studio/composer.json

**Motivation**
Fixes #ACMS-4414
Move method from common to site studio and replace accordingly.
NA

ACMS-4414: Move method from common to site studio and replace accordingly.

---

.github/workflows/acquia_cms_ci.workflow.yml
composer.json
composer.lock
modules/acquia_cms_article/tests/src/Functional/ArticlePermissionsTest.php
modules/acquia_cms_audio/tests/src/Functional/AudioTest.php
modules/acquia_cms_common/acquia_cms_common.info.yml

This pull request updates the `composer.json` file to expand the version compatibility for a development dependency.
Dependency version compatibility:
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L41-R41): Updated the `acquia/coding-standards` version constraint in the `require-dev` section to allow compatibility with versions `^1.0`, `^2.0`, and `^3.0`.

Update acquia/coding-standards dependency.

---

composer.lock
modules/acquia_cms_common/acquia_cms_common.info.yml
modules/acquia_cms_common/composer.json
modules/acquia_cms_common/src/EventSubscriber/ConfigEventsSubscriber.php
modules/acquia_cms_headless/composer.json
modules/acquia_cms_image/acquia_cms_image.install
modules/acquia_cms_page/acquia_cms_page.module
modules/acquia_cms_page/tests/src/Kernel/PageWithLayoutCanvasFieldTest.php
modules/acquia_cms_search/acquia_cms_search.info.yml
modules/acquia_cms_search/tests/src/FunctionalJavascript/AcquiaFacetSearchTest.php
modules/acquia_cms_site_studio/acquia_cms_site_studio.install

**Motivation**
Fixes #ACMS-4953
Fix acms:install with Drupal 11.2.2
NA
```
composer create-project acquia/drupal-recommended-project project && cd project
./vendor/bin/acms acms:install
```

ACMS-4953: Acquia CMS Fails to Install.
