acquia/acquia_cms

- acquia_cms.profile
- drush/Commands/SiteInstallCommands.php
https://backlog.acquia.com/browse/ACMS-696 [SPIKE]
**Motivation**
_We currently rebuild cohesion assets after install in order to avoid timeout errors, but if we can run threaded tasks, we might improve our install experience.
_Issue_
timeout errors
Fixes #NNN
Investigate Symfony libraries for asynchronous threaded install tasks
-we could try drush post command hook and run cohesion rebuild from there
look in to Symfony\Component\Process\Process 
Find if f there is a way to run a block of code directly (no we cannot call a class directly for example check docroot/core/tests/Drupal/Tests/Core/Command/QuickStartTest.php)
Another simpler option could be to modify the acquia_cms_rebuild_cohesion() function so that it tests if the request is …
> ACMS-696: Post command hook approach to run rebuild after site install.

- modules/acquia_cms_page/config/install/core.entity_view_display.node.page.search_index.yml
**Motivation**
`Overlong word` error coming from search API when enabling Starter
Enable search index view mode and remove layout canvas field from it, since we are using this view mode in index, but did not create it, hence the index was using default view mode for page, which has layout canvas field, that is the root cause that layout canvas field was getting indexed, as part of rendered html field.
Stop tokeniser to tokenise cohesion component, or remove cohesion component from index
install site, add a new page with a site studio component, and there should noit be a overlong word log, also this warning should not appear when we enable starter module.
> ACMS-720: Overlong word waring fix by removing coh comp from index

- install-acms
**Motivation**
Since, we are now Rebuilding cohesion using drush post-command hook, so when we do site install using command: composer acms:install, cohesion rebuild runs twice.
Fixes #NNN
Remove rebuild code from install-acms script
> ACMS-696: Remove rebuild code from install-acms script

- drush/Commands/SiteInstallCommands.php
- modules/acquia_cms_article/config/optional/block.block.articles_article_type.yml
- modules/acquia_cms_article/config/optional/block.block.articles_category.yml
- modules/acquia_cms_article/config/optional/block.block.search_article_type.yml
- modules/acquia_cms_common/config/optional/block.block.search_category.yml
- modules/acquia_cms_common/config/optional/block.block.search_content_type.yml
- modules/acquia_cms_common/src/Commands/AcmsConfigImportCommands.php
- modules/acquia_cms_common/src/Services/AcmsUtilityService.php
- modules/acquia_cms_event/config/optional/block.block.events_category.yml
- modules/acquia_cms_event/config/optional/block.block.events_event_type.yml
- modules/acquia_cms_event/config/optional/block.block.search_event_type.yml
- modules/acquia_cms_person/config/optional/block.block.people_category.yml
- modules/acquia_cms_person/config/optional/block.block.people_person_type.yml
- modules/acquia_cms_person/config/optional/block.block.search_person_type.yml
- modules/acquia_cms_place/config/optional/block.block.places_category.yml
- modules/acquia_cms_place/config/optional/block.block.places_place_type.yml
- modules/acquia_cms_place/config/optional/block.block.search_place_type.yml
- modules/acquia_cms_video/config/optional/core.entity_view_display.media.video.default.yml
**Motivation**
ACMS-702
Fixes #NNN
Improvement in drush command 
```
drush acms:config-reset
```
Run `acms:config-reset` drush command with variations and check all are working fine.
Interactive:
```
drush acms:config-reset
drush acms:config-reset acquia_cms_article,acquia_cms_person,acquia_cms_place
drush acms:config-reset acquia_cms_article acquia_cms_person acquia_cms_place --scope=all
```
Non-interactive:
```
drush acms:config-reset acquia_cms_article acquia_cms_person acquia_cms_place --scope=all -y
```
> ACMS-702: Further improvement needed for drush command 'acms:config-reset'

- composer.json
- composer.lock
**Motivation**
Fixes ohesion rebuild not happening on site install in aquia-cms-project
Add scaffold in composer.json
I checked earlier in acquia_cms, including command in common module does not work, hence i had put it in drush/Commands in this PR (https://github.com/acquia/acquia_cms/pull/750/files)
drush/Commands/SiteInstallCommands.php works 
modules/acquia_cms_common/src/Commands/SiteInstallCommands.php does not works
acquia-cms-project
However for acms-project keeping file in below paths is not working
docroot/profiles/contrib/acquia_cms/drush/Commands/SiteInstallCommands.php does not works
docroot/profiles/contrib/acquia_cms/modules/acquia_cms_common/src/Commands/SiteInstallCommands.php does not works
Only below path works, i tried …
> ACMS-734: Add a scaffold to copy fle to acms-project

- modules/acquia_cms_starter/content/node/0098ef73-f5d3-4b91-b376-62e01d6892b3.yml
- modules/acquia_cms_starter/content/node/0ff5fe80-f6d5-471e-a922-990b4037c9e7.yml
- modules/acquia_cms_starter/content/node/167cb9be-e752-419e-a4cc-060abce792a0.yml
- modules/acquia_cms_starter/content/node/1fc224b3-849d-43fc-b0c1-cd4d6e1e3fbb.yml
- modules/acquia_cms_starter/content/node/2de584f5-f689-400e-b137-4744f2a1f68f.yml
- modules/acquia_cms_starter/content/node/6543ad81-8fdb-4852-b842-e665aa1788b6.yml
- modules/acquia_cms_starter/content/node/8aef96ff-8e68-4d88-b6bd-28ff8a227eb3.yml
- modules/acquia_cms_starter/content/node/8ca3c322-4b7f-43d0-a37d-d883ef9b7e5b.yml
- modules/acquia_cms_starter/content/node/922a4cef-f334-4e0b-87f8-7b31da9393bc.yml
- modules/acquia_cms_starter/content/node/96b0a01f-6d06-46ef-959c-8d96343c88a8.yml
- modules/acquia_cms_starter/content/node/a0fc7bd8-f7dd-4468-bc77-d154c374c686.yml
- modules/acquia_cms_starter/content/node/a1eafd08-eaec-4f57-be82-e93c81be9d62.yml
- modules/acquia_cms_starter/content/node/af87f256-f648-48d5-be0d-7e0e0616331a.yml
- modules/acquia_cms_starter/content/node/e213202d-56f1-4e72-862c-e55d9ca19afe.yml
- modules/acquia_cms_starter/content/node/f01ed833-ec04-41d9-967c-45b04c6e3b12.yml
- modules/acquia_cms_starter/content/node/f4b3eb8e-234a-4788-9ba7-6e8838b362d2.yml
**Motivation**
Updated the created date to list the content in order that matches the reference image for backstop for artifacts to pass.
Fixes #742
Updated the created date to list the content in order that matches the reference image for backstop for artifacts to pass.
We cannot update the reference image hence considered the change in creation date to duplicate the order as per the reference image.
To test, create artifacts from Cloud IDE following this document - https://github.com/acquia/acquia_cms/wiki/Test-Artifact-Creation, once artifacts are created and committed, notice that the travis job does not return any error related to the following file - backstop_default_ACMS_Articles_Starter_0_document_0_mobile.png …
> ACMS-742: Updated created date for the content listing order to match the reference image.

- patches/d9-acms-settings.patch
https://backlog.acquia.com/browse/ACMS-763
**Motivation**
Acquia CMS errors out in CloudIDE
Check that function exists in patches/d9-acms-settings.patch:
// Only call this function on the cloud, not on a local environment.
if (function_exists(acquia_hosting_db_choose_active) {
acquia_hosting_db_choose_active();
} 
Following the installation steps for Acquia CMS from: https://docs.acquia.com/acquia-cms/install-acquia-cms/ -> https://github.com/acquia/acquia-cms-project should work in the Cloud IDE, and local.
> ACMS-763: Acquia CMS errors out in CloudIDE

- modules/acquia_cms_article/acquia_cms_article.info.yml
- modules/acquia_cms_audio/acquia_cms_audio.info.yml
- modules/acquia_cms_common/acquia_cms_common.info.yml
- modules/acquia_cms_document/acquia_cms_document.info.yml
- modules/acquia_cms_event/acquia_cms_event.info.yml
- modules/acquia_cms_image/acquia_cms_image.info.yml
- modules/acquia_cms_page/acquia_cms_page.info.yml
- modules/acquia_cms_person/acquia_cms_person.info.yml
- modules/acquia_cms_place/acquia_cms_place.info.yml
- modules/acquia_cms_search/acquia_cms_search.info.yml
- modules/acquia_cms_toolbar/acquia_cms_toolbar.info.yml
- modules/acquia_cms_tour/acquia_cms_tour.info.yml
- modules/acquia_cms_video/acquia_cms_video.info.yml
**Motivation**
Fixes #[ACMS-772](https://backlog.acquia.com/browse/ACMS-772)
Update module's name in info file
Visit extend page and verify all acms module name should have prefix "Acquia CMS"
> ACMS-772: Update all Acquia CMS modules name to have prefix "Acquia CMS"

- config/install/image.style.coh_large_landscape.yml
- config/install/image.style.coh_large_super_landscape.yml
- config/install/image.style.coh_medium_landscape.yml
- config/install/image.style.coh_medium_super_landscape.yml
- config/install/image.style.coh_small_landscape.yml
- config/install/image.style.coh_small_square.yml
- config/install/image.style.coh_x_large_landscape.yml
- config/install/image.style.coh_x_large_super_landscape.yml
- config/install/image.style.coh_xx_large_landscape.yml
- config/install/image.style.coh_xx_small_landscape.yml
- modules/acquia_cms_common/acquia_cms_common.info.yml
- modules/acquia_cms_common/config/install/image.style.coh_large_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_large_super_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_medium_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_medium_super_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_small_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_small_square.yml
- modules/acquia_cms_common/config/install/image.style.coh_x_large_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_x_large_super_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_xx_large_landscape.yml
- modules/acquia_cms_common/config/install/image.style.coh_xx_small_landscape.yml
**Motivation**
* The Drupal Image Styles have effect Scale and Crop and hence the focal point doesn't work while the image is uploaded.
Fixes #ACMS-771
* Selected Image styles were updated with the effect - Focal Point Scale and Crop from Scale and Crop. (See attached google Sheet and screenshot of the changes made)
* None
* To test, head towards content creation page and create a content of type page.
* In the layout canvas field, added a component example - Image. 
* Upload a new image and once the image is uploaded in the pop up window, you will notice that image preview has a pointer that can be moved to change the focus point of the image on the UI.
* Move the focus point to different positions from center of the …
> ACMS-771: Changed the image style from scale and crop to focal point scale and crop.

- composer.json
- composer.lock
Drupal 9 core version constraints changed from `~9.1.9` to `^9.1.9`  so that our project runs on drupal core 9.2.x and our existing isolate tests gets executed and passed.
> ACMS-783: version constraint updated to allow run tests on drupal core 9.2.x

- acquia_cms.profile
**Motivation**
Improves drush-based site install time significantly.
We had this logic backwards. Rebuilds should be skipped on _non-interactive_ installs (e.g., drush).
Run a drush based site install of ACMS.
> ACMS-780: Rebuilds should be skipped during non-interactive install.

- modules/acquia_cms_tour/css/acquia_cms_tour_dashboard.css
- modules/acquia_cms_tour/src/Form/AcquiaConnectorForm.php
- modules/acquia_cms_tour/src/Form/AcquiaGoogleMapsApiDashboardForm.php
- modules/acquia_cms_tour/src/Form/AcquiaSearchForm.php
- modules/acquia_cms_tour/src/Form/AcquiaTelemetryForm.php
- modules/acquia_cms_tour/src/Form/GoogleAnalyticsForm.php
- modules/acquia_cms_tour/src/Form/GoogleTagManagerForm.php
- modules/acquia_cms_tour/src/Form/RecaptchaForm.php
- modules/acquia_cms_tour/src/Form/SiteStudioCoreForm.php
**Motivation**
* There should be a description beside the Advance button on Admin tour dashboard page.
Fixes #ACMS-760
* Add an "i" button beside the Advance link to show the description of what Advance does.
* The button shows information on hover/click.
* NONE
* To test, head towards /admin/tour/dashboard and notice that there are different form tabs
* Open a form tab and notice the "i" button beside Advance link (check screenshot)
* Hover over the "i" button to see the tooltip getting displayed.
**Screenshot Attached**
> ACMS-760: Added code for displaying the tooltip beside Advance button.

- DEVELOPING.md
**Motivation**
The cloud IDE setup fails at step - `composer install` due to extension errors.
Fixes #ACMS-780
Updated the document as per the demo framework document here - https://confluence.acquia.com/display/DF/Remote+IDE
NONE
Test by setting up the project using cloud IDE setup steps in project setup documentation.
> ACMS-780: Updated document with the cloud IDE installation steps for extension.

- package.json
- tests/backstop/backstop-settings.js
**Motivation**
We should be able to run the backstop and pa11y commands from IDE.
Fixes #690 
- Added code to separate out the commands for IDE.
-  NONE
- Head towards terminal on your PC and run the following commands to test.
- npm run backstop-starter - Runs on both IDE and local
- npm run pa11y-starter
- npm run pa11y-starter-ide
- [* ] Manual testing by a reviewer
> ACMS-587: Configuration of backstop using a js settings file

- modules/acquia_cms_toolbar/acquia_cms_toolbar.module
- modules/acquia_cms_toolbar/js/acms_toolbar.js
**Motivation**
Fixes #[ACMS-810](https://backlog.acquia.com/browse/ACMS-810)
- Install acquia cms and configure content hub.
-  Visit admin/content/acquia-contenthub and make sure you can see content hub interface.
> ACMS-810: Fix Content Hub UI broken and blank in ACMS

- composer.json
- composer.lock
**Motivation**
* The breadcrumb shows an empty space in between "Home" & "Add Content" on node add pages.
Fixes #ACMS-814
* As per the latest release (9.2.0) following issue was created : https://www.drupal.org/node/2716019
* The changes made to the Drupal Core are in the patch : https://www.drupal.org/files/issues/2021-04-22/2716019-156.patch
* As per the comment here: https://www.drupal.org/project/drupal/issues/2716019#comment-14069261 the breadcrumb will now pick up the title from "View" itself. 
* Hence, in our case "None" was resulting in an empty space. After changing this to "Node" the issue is now fixed.
* Created the patch for core and added it in composer json file.
* None
* Head towards : node/add/article or …
> ACMS-814: Changed the view title from none to node for frontpage view.

- acquia_cms.profile
- src/Commands/SiteInstallCommands.php
**Motivation**
* We need to calculate and send the install & rebuild start and end time to acquia telemetry
Fixes #ACMS-768
* Add the install start time and end time and rebuild start time and end time and calculate the difference between the two & send to acquia telemetry via heartbeat_event in acquia_cms.profile
* None
<Pending>
> ACMS-768: Added code for logging time for install rebuild start & end.

- composer.json
- composer.lock
**Motivation**
* The breadcrumb shows an empty space in between "Home" & "Add Content" on node add pages.
Fixes #ACMS-814
* As per the latest release (9.2.0) following issue was created : https://www.drupal.org/node/2716019
* The changes made to the Drupal Core are in the patch : https://www.drupal.org/files/issues/2021-04-22/2716019-156.patch
* As per the comment here: https://www.drupal.org/project/drupal/issues/2716019#comment-14069261 the breadcrumb will now pick up the title from "View" itself. 
* Hence, in our case "None" was resulting in an empty space. After changing this to "Node" the issue is now fixed.
* Created the patch for core and added it in composer json file.
* None
* Head towards : node/add/article or …
> ACMS-814: Fixed the missing piece of code in the patch.

- modules/acquia_cms_search/acquia_cms_search.info.yml
- modules/acquia_cms_search/acquia_cms_search.install
- modules/acquia_cms_search/composer.json
- modules/acquia_cms_search/config/install/views.view.search.yml
- modules/acquia_cms_search/config/install/views.view.search_fallback.yml
- modules/acquia_cms_search/src/Facade/SearchFacade.php
- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
**Motivation**
Fixes #[ACMS-835](https://backlog.acquia.com/browse/ACMS-835)
Update search view display option programatically to use `cohesion_layout` if `acquia_cms_site_studio` module is present and enabled else leave to use default.
Add `acquia_cms_site_studio` module dependency in `acquia_cms_search`
**Scenario 1:**
- Create vanilla drupal project along with custom profile refer : https://github.com/acquia/acquia_cms/blob/feature/profile-refactor/CUSTOM_PROFILE/README.md 
- Install site using custom profile created above.
- Creates some content like , article, person & place.
- Visit search page (/search) and verify that you can see result using default theme olivero template.
- Now set fallback search view  by …
> ACMS-835: Remove Site Studio dependency from acquia_cms_search

- composer.json
- composer.lock
- src/Form/SiteConfigureForm.php
**Motivation**
Fixes access denied issue when cohesion module is installed during site installation.
Created a patch in Site Studio (cohesion) module which causing the access denied error.
Alternate patch is tried as provided by Site Studio team (i.e https://backlog.acquia.com/secure/attachment/323751/323751_ACO-1169.patch) but it didn't solve the actual issue.
- Install the Site using UI (without adding Site Studio keys in Site Configuration page). After site installation is completed, user shouldn't be redirected to Access Denied page.
- Install the Site using UI (adding Site Studio keys in Site Configuration page). After site installation is completed, user shouldn't be redirected to Access Denied page.
**Merge …
> ACMS-834: Created patch in Site Studio module to fix Access denied error.

- DEVELOPING.md
**Motivation**
* We need to update the steps to run the tests in documentation [here](https://github.com/acquia/acquia_cms/blob/develop/DEVELOPING.md) to be able to run the tests successfully without the --group option
Fixes #[ACMS-845](https://backlog.acquia.com/browse/ACMS-845)
* Update the steps to run the tests in documentation [here](https://github.com/acquia/acquia_cms/blob/develop/DEVELOPING.md) to be able to run the tests successfully without the --group option
* None
* Follow the steps mentioned in ticket / developing documentation to run the tests succesfully.
> ACMS-845: Updated the documentation to replace the --group option with actual module name.

- .travis.yml
**Motivation**
Fixes ACMS-861
Add an ORCA job for the previous minor Drupal version, and only run it on cron builds.
N/A
Ensure test runs on cron build.
> ACMS-861: Add ORCA job to test with previous minor Drupal version

- composer.json
- composer.lock
**Motivation**
Fixes ACMS-862
This update to the beta3 version of Moderation Dashboard and removes the patch that no longer applies. This is necessary to be compatible with other Acquia packages for integrated testing.
N/A
Once released, ORCA INTEGRATED_TEST_ON_CURRENT_DEV jobs should pass using the dev branch of drupal-recommended-project.
> ACMS-862: Update Moderation Dashboard and remove patch.

- modules/acquia_cms_common/acquia_cms_common.services.yml
- modules/acquia_cms_search/acquia_cms_search.info.yml
**Motivation**
Fixes #[ACMS-878](https://backlog.acquia.com/browse/ACMS-878)
Fix tests failure for combinations of module in isolation for example using (article, acquia_cms_search & acquia_cms_page) module.
NA
Install site with custom profile and run test for acquia_cms_artile and make sure that following module is enabled as part of custom profile install - 
- acquia_cms_search
- acquia_cms_page
- acquia_cms_article
> ACMS-878: Fix test failure in isolation with custom profile

- modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
**Motivation**
Fixes Invalid module dependencies updated on acquia_cms_site_studio.info config.
Updated acquia_cms_site_studio.info.yml config with correct dependencies.
N/A
Run command: composer require drupal/acquia_cms_site_studio. It should download module without reporting any error.
> ACMS-883: Invalid module dependencies updated on acquia_cms_site_studio.info config.

- modules/acquia_cms_search/acquia_cms_search.info.yml
**Motivation**
* The search bar on search result page is resulting in an incorrect styling of the search result bar.
Fixes #NNN
* The module required for proper styling of the module was not getting enabled when search functionality is installed and enabled in isolated environment using custom profile.
* None
* Install the site in an isolated environment using a custom profile and install the following modules - 
* `composer require drupal/acquia_cms_article drupal/acquia_cms_audio drupal/acquia_cms_document drupal/acquia_cms_event drupal/acquia_cms_page drupal/acquia_cms_search drupal/acquia_cms_toolbar drupal/acquia_cms_video`
* You can use the following profile for testing - https://github.com/chandan-singh7929/starter …
> ACMS-891: Added dependency for search api autocomplete module.

- modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
- modules/acquia_cms_site_studio/composer.json
**Motivation**
Fixes ACMS-893
Adds ACMS Common module as a dependency for ACMS Site Studio module.
N/A
ACMS Site Studio module should be installable in the absence of all other ACMS component modules.
> ACMS-893: Add acquia_cms_common dependency to acquia_cms_site_studio.

- acquia_cms.services.yml
- src/EventSubscriber/HttpsRedirectSubscriber.php
**Motivation**
* The BLT tests fail because of the HTTPS enforced status code.
Fixes #[ACMS-819](https://backlog.acquia.com/browse/ACMS-819)
* Add a remote address condition in code to check the URL is not a localhost URL.
* None
* Setup Acquia CMS using BLT
* Run a BLT related test and observe that the tests complete successfully.
> ACMS-819: Added condition to check for remote address.

- config/optional/reroute_email.settings.yml
- drush/drush.yml
- hooks/common/post-code-deploy/install_acms.sh
- hooks/common/post-code-update/install_acms.sh
- modules/acquia_cms_common/acquia_cms_common.module
**Motivation**
* The email id configured at various places is no reply acquia. It should be changed to no reply example.
Fixes #NNN
* Change email ID to no reply example.
* None
* Check that all places have new email ID configured and the mail is only sent if the mail id is changed.
> ACMS-839: Changed the email ID to example no reply.

- modules/acquia_cms_common/src/EventSubscriber/ConfigEventsSubscriber.php
- modules/acquia_cms_event/acquia_cms_event.install
- modules/acquia_cms_event/config/optional/views.view.event_cards.yml
- modules/acquia_cms_event/tests/src/ExistingSite/PastEventsBlockTest.php
**Motivation**
Fixes #[ACMS-917](https://backlog.acquia.com/browse/ACMS-917)
Update past event view display to use cohesion template with display title changes.
NA
- Install Acquia CMS.
- Enable starter module.
- Create some events with past date.
- Add past event block on page.
- Verify its displaying correctly.
- Now visit past events views block `/admin/structure/views/view/event_cards/edit/upcoming_events_block` and make sure nothing is broken.
> ACMS-917: Acquia CMS's Event Cards view block broken OOTB

- modules/acquia_cms_image/composer.json
**Motivation**
* Added patch for Acquia CMS Image dependency on default content
Fixes #NNN
* * Added patch for Acquia CMS Image dependency on default content
* None
* none
> ACMS-912: Added patch for default content module for Acquia CMS Image.

- modules/acquia_cms_starter/content/node/1761acce-1b37-4359-944f-abbeb34097d4.yml
- modules/acquia_cms_starter/content/node/493e1456-3ec1-4696-903e-3d21e2612ea3.yml
- modules/acquia_cms_starter/content/node/4e5945c9-3f3f-4785-b864-d24b6fad041a.yml
- modules/acquia_cms_starter/content/node/79f98237-e9e8-435a-b462-b240a59d0986.yml
- modules/acquia_cms_starter/content/node/9ca2f5ef-2134-4999-acca-53ec55d7e926.yml
- modules/acquia_cms_starter/content/node/c99c8891-79ff-48db-abeb-87d477e944bc.yml
**Motivation**
Fixes #[ACMS-918](https://backlog.acquia.com/browse/ACMS-918)
Update events content title created by starter module.
NA
- Install acquia cms with site studio key.
- Enable start module.
- Place event slider component on home page, which by default place upcoming block.
- Visit home page you will notice upcoming block has with title past event. 
> ACMS-918: Starter module create event content with title past event

- acquia_cms.info.yml
**Motivation**
* The install new module link redirects to access denied page.
Fixes #NNN
* Remove the update module from profile info file.
* None
* After merge, verify that install new module link is no longer available and also the update module is disabled.
> ACMS-882: Removed the update manager module from profile info file.

- composer.json
- composer.lock
**Motivation**
Fix failing CI job. It's failing due to purge module next version released and we've patches included which is now included in the next release.
Reverted acquia_purge pinned module change from PR: https://github.com/acquia/acquia_cms/pull/952
> ACMS-925: Patches removed as purge module updated.

- composer.json
- composer.lock
**Motivation**
Revert changes for ACMS-925. We no longer need purge module patches as it's already incorporated in next release for purge module i.e v3.2 of purge module
Reverted commits of ticket ACMS-925 contains in the following PR:
1. https://github.com/acquia/acquia_cms/pull/952
2. https://github.com/acquia/acquia_cms/pull/958
> ACMS-925: Reverted changes.

- modules/acquia_cms_site_studio/acquia_cms_site_studio.module
Fixes the ExistingSiteJavascript test failure
**Motivation**
Fixes the issue for ExistingSiteJavascript test failure during CRON runs
Updated the config `cohesion.settings` to set default sidebar view to: Show Title. This issue is most probably caused due to [ACMS-935](https://backlog.acquia.com/browse/ACMS-935) as we've removed the `cohesion.settings` config, which we've provided in config/install directory (earlier) and we've now programatically imported the config during site install.
- Install the site with Site Studio.
- Run the following tests: `docroot/profiles/contrib/acquia_cms/tests/src/ExistingSiteJavascript/AccordionComponentTest.php` and this should pass.
> ACMS-952: Update cohesion.setting config to set default sidebar view.

- modules/acquia_cms_starter/acquia_cms_starter.install
**Motivation**
* The module acquia_cms_starter is not enabled when enabled using UI. The module should be enabled and a warning should be displayed as it is displayed when we enable the module using drush.
Fixes #[ACMS-955](https://backlog.acquia.com/browse/ACMS-955)
* Added hook_modules_installed() to install the module and display the warning message for MAPS API key not set.
* The warning message could also be displayed by setting 'severity' => REQUIREMENT_WARNING in hook_requirements hook.
* But this doesn't work and the warning message is completely ignored in case of UI installation method.
* Check the issue link here - https://www.drupal.org/project/drupal/issues/2295051
* Enable the module using UI module enabling …
> ACMS-955: Added code to display message on module install using UI.

- tests/src/ExistingSiteJavascript/CohesionElement.php
- tests/src/ExistingSiteJavascript/CohesionTestBase.php
- tests/src/ExistingSiteJavascript/SearchTest.php
- tests/travis/install.sh
**Motivation**
Fixes `STRICT_DEPRECATED_CODE_SCAN` travis job.
The method `$element->getSession()` has been marked as deprecated from mink: 1.6. See [here](https://github.com/minkphp/Mink/blob/master/CHANGES.md#160--2014-09-26). 
In class CohesionElement.php (tests/src/ExistingSiteJavascript/CohesionElement.php) we've used `$element->getSession()` & `$this->getSession()` at multiple places. But since the method `getSession()` from element is marked as deprecated, so it's giving error. To fix this, we've added a protected variable `$session` in the class and use that instead everywhere (where session is required)
N/A
In order to test in local, we need drupal-check command. Use the following commands to download drupal-check …
> ACMS-976: Fixed deprecated code warnings: Call to deprecated method getSession().

- composer.json
- composer.lock
- modules/acquia_cms_common/acquia_cms_common.module
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_common/tests/src/Functional/NodeBreadcrumbTest.php
**Motivation**
Fixes the patch failing issue on Drupal 9.3
- Removed the patch and added hook_system_breadcrumb_alter() to set breadcrumb texts for node create/edit page (if it's empty)
Tried to use following composer plugin: https://github.com/netresearch/composer-patches-plugin but it's not working and giving error. It looks like it's conflicting with the composer plugin which we are using currently 
i.e `cweagans/composer-patches`
- Go to any content type create page and there you should see breadcrumb as: `Home -> Node -> Add content`.
- Go to any node edit page and there you should see breadcrumb as: `Home -> <Node Title>`.
- Navigate to Frontpage view (i.e /admin/structure/views/view/frontpage) & change to display …
> ACMS-979: Fixed the patch failing issue on Drupal 9.3

- modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
**Motivation**
Fixes #[ACMS-997](https://backlog.acquia.com/browse/ACMS-997)
Enable Site Studio Visual Page Builder module by default in acquia_cms profile
NA
- Install site with acquia_cms profile
- Visite extend page (admin/modules)
- Make sure sitestudio_page_builder module enable by default
> ACMS-997: Enable Site Studio Visual Page Builder

- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-1018](https://backlog.acquia.com/browse/ACMS-1018)
Upgrade reroute module to latest.
NA
> ACMS-1018: Reroute 2.0.2 Email No Longer Supported

- modules/acquia_cms_component/components/block/react_component_block/react_node_block.js
**Motivation**
Fixes #[ACMS-1012](https://backlog.acquia.com/browse/ACMS-1012)
When React node component block is configured with page/ place node type, the contents of React Node Component Block on the site showing 'No Results' even if the page and place content is available in site
NA
- Click on edit button, on js component block
- Select 'Choose the Node type' as page/ place
- Save
- Check for the React block on the main site 
- [_Bug_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
> ACMS-1012: JS Component : Place and page content are not visible

- acquia_cms.profile
Fixed issue: Acquia CMS icon not appearing when using Drupal profile.
**Motivation**
Fixes issue for Acquia CMS icon not appearing on Acquia Cloud.
N/A.
N/A
Install Acquia CMS profile on Acquia Cloud using drush and you should see Acquia CMS icon.
> ACMS-812: Fixed issue: Acquia CMS icon not appearing when using Drupal profile.

- composer.json
- composer.lock
- modules/acquia_cms_privacy/composer.json
**Motivation**
gdpr module updated to 3.0.0-alpha5 release.
Update composer dependencies to gdpr alpha5 version.
N/A
Install and enable acquia_cms_privacy module
> ACMS-644: gdpr module updated to 3.0.0-alpha5 release.

- modules/acquia_cms_common/tests/src/ExistingSite/ContentTypeListTestBase.php
- tests/travis/install.sh
**Motivation**
Fixes #[ACMS-1024](https://backlog.acquia.com/browse/ACMS-1024)
Update test cases so all test pass on travis as well as locally.
NA
- Install site using SS studio key 
- Run local test suite and make sure all test are passing
- Check overnight build and make sure all test have passed, except for the one below and those which are allowed to fail
https://app.travis-ci.com/github/acquia/acquia_cms/jobs/553742693 - We have separate issue in ORCA
- [_Bug_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
> ACMS-1024: Fix travis jobs failure

- themes/acquia_claro/acquia_claro.theme
- themes/acquia_claro/templates/status-report-general-info.html.twig
**Motivation**
Fixes #[ACMS-1031](https://backlog.acquia.com/browse/ACMS-1031)
We should have the ACMS version with the Drupal version displayed on the status report page after the ACMS site is installed under 'General System Information' as a card. Which will give the user/ consumer visibility after installation. 
NA
- Install site with acquia_cms
- Navigate to status report page (admin/reports/status) and make sure you see card with acquia CMS information
> ACMS-1031: ACMS version on ACMS site status report page

- modules/acquia_cms_audio/acquia_cms_audio.info.yml
- modules/acquia_cms_audio/acquia_cms_audio.install
- modules/acquia_cms_audio/composer.json
- modules/acquia_cms_audio/config/optional/core.entity_form_display.media.audio.default.yml
- modules/acquia_cms_audio/config/optional/core.entity_form_display.media.audio.media_library.yml
- modules/acquia_cms_audio/config/optional/core.entity_form_mode.media.media_library.yml
- modules/acquia_cms_audio/config/optional/core.entity_view_display.media.audio.default.yml
- modules/acquia_cms_audio/config/optional/core.entity_view_display.media.audio.embedded.yml
- modules/acquia_cms_audio/config/optional/core.entity_view_display.media.audio.media_library.yml
- modules/acquia_cms_audio/config/optional/core.entity_view_mode.media.embedded.yml
- modules/acquia_cms_audio/config/optional/core.entity_view_mode.media.media_library.yml
- modules/acquia_cms_audio/config/optional/field.field.media.audio.field_categories.yml
- modules/acquia_cms_audio/config/optional/field.field.media.audio.field_media_soundcloud.yml
- modules/acquia_cms_audio/config/optional/field.field.media.audio.field_tags.yml
- modules/acquia_cms_audio/config/optional/field.storage.media.field_media_soundcloud.yml
- modules/acquia_cms_audio/config/optional/language.content_settings.media.audio.yml
- modules/acquia_cms_audio/config/optional/media.type.audio.yml
- modules/acquia_cms_audio/tests/src/Functional/AudioTest.php
**Motivation**
Fixes #[ACMS-913](https://backlog.acquia.com/browse/ACMS-913)
- Require the Media Entity Soundcloud module in the acquia_cms_audio module to provide a simple hosted audio option.
- Add an Audio media type using soundcloud url as the source field with display using the embedded soundcloud option.
- Write PHPUnit tests.
NA
- Install site using acquia_cms profile
- Check media type, you should see new media type called audio
- Try to add audio media type by providing sound cloud audio track URL
- It should create audio media
> ACMS-913: Enabling acquia_cms_audio does not add Audio media type

- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-913](https://backlog.acquia.com/browse/ACMS-913)
- Require the Media Entity Soundcloud module in the acquia_cms_audio module to provide a simple hosted audio option.
- Add an Audio media type using soundcloud url as the source field with display using the embedded soundcloud option.
- Write PHPUnit tests.
NA
- Install site using acquia_cms profile
- Check media type, you should see new media type called audio
- Try to add audio media type by providing sound cloud audio track URL
- It should create audio media
> ACMS-913: Add module media_entity_soundcloud in composer.json

- composer.json
- composer.lock
- modules/acquia_cms_search/composer.json
**Motivation**
* unable to deselect selected facet.
Fixes #NNN
* Revert code in the new version of the module.
* None
* Instal site and install facet and search module and filter result from facet.
* Notice that deselecting the facet doesn't work without the patch.
> ACMS-1042: Added patch for facet reset link failure.

- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
**Motivation**
Fixes #[ACMS-1057](https://backlog.acquia.com/browse/ACMS-1057)
After upgrading ACMS to version 1.4.1 from version 1.4.0 I can no longer install my site from configuration because of an error with site_studio_page_builder.
Steps to Reproduce
Install ACMS 1.4.0 and export the configuration. 
Upgrade to ACMS 1.4.1 and export the configuration.
Run blt setup again with blt having the following config:
```
cm: 
strategy: config-split 
core: 
path: ../config 
dirs: { sync: { path: '${cm.core.path}/default' } }
install_from_config: false
```
> ACMS-1057: Enable sitestudio_page_builder module by default

- composer.json
- composer.lock
- modules/acquia_cms_article/composer.json
- modules/acquia_cms_audio/composer.json
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_component/composer.json
- modules/acquia_cms_development/composer.json
- modules/acquia_cms_document/composer.json
- modules/acquia_cms_event/composer.json
- modules/acquia_cms_image/composer.json
- modules/acquia_cms_page/composer.json
- modules/acquia_cms_person/composer.json
- modules/acquia_cms_place/composer.json
- modules/acquia_cms_search/composer.json
- modules/acquia_cms_site_studio/composer.json
- modules/acquia_cms_starter/composer.json
- modules/acquia_cms_support/composer.json
- modules/acquia_cms_toolbar/composer.json
- modules/acquia_cms_tour/composer.json
- modules/acquia_cms_video/composer.json
- tests/travis/install.sh
- themes/acquia_claro/composer.json
**Motivation**
Fixes #[1060](https://backlog.acquia.com/browse/ACMS-1060)
- Update composer to ^2.2
- add plugins in allowed section
NA
- update composer to ^2.2
- run composer install
- it should not be blocked by any plugins when running composer install
> ACMS-1060: Add allowed plugins in Composer

- patches/d9-acms-settings.patch
- patches/maintenance_theme.settings.patch
**Motivation**
Fixes #[ACMS-965](https://backlog.acquia.com/browse/ACMS-965)
QA environment should be up and running
NA
- Visit http://orionacmsode1.prod.acquia-sites.com and verify application.
> ACMS 965: ACMS QA Environment is down

- composer.json
- composer.lock
**Motivation**
Fixes #[1049](https://backlog.acquia.com/browse/ACMS-1049)
Update Drush to 11
NA
- Run `composer install`
- Run `drush status` OR `drush -v`
- Check drush version should be updated to 11
> ACMS-1049: Update to Support Drush 11

- composer.lock
**Motivation**
Fixes #[ACMS-1067](https://backlog.acquia.com/browse/ACMS-1067)
Update Drupal modules to latest.
- ACSF: 2.71.0
- Acquia ContentHub: 2.30.0
- Webform: 6.1.3
NA
- Login to https://orionacmsdev.prod.acquia-sites.com as administrator
- Head towards /admin/modules 
- Verify that modules are up to date
> ACMS-1067: Update contrib modules - not enabled

- composer.json
- composer.lock
**Motivation**
Upgrade Drupal core to 9.3.7
Update composer.json & composer.lock file to get the latest Drupal core i.e v9.3.7
N/A.
Navigate to Status Report page and you should see Drupal core version as 9.3.7.
> ACMS-1085: Update Drupal core to 9.3.7.

- acms-run-tests.sh
**Motivation**
Fixes #[ACMS-847](https://backlog.acquia.com/browse/ACMS-847)
When running the tests using ACMS tests script (i.e ./acms-run-tests.sh), we are getting connection refused error.
- Make sure drush CLI is not installed as a global dependency or when we run command `drush status` from any of the directory (ex: user's home directory), we should get command not found error.
- Run the below command to run ACMS tests and you'll get connection refused error:
```
./acms-run-tests.sh
```
> ACMS-847: Connection refused error when running tests

- modules/acquia_cms_tour/acquia_cms_tour.module
- modules/acquia_cms_tour/src/Controller/TourController.php
- modules/acquia_cms_tour/templates/acquia-cms-tour.html.twig
- modules/acquia_cms_tour/tests/src/Functional/GetStartedButtonTest.php
**Motivation**
* Added condition in twig file for role based button display.
Fixes #NNN
* Added condition in twig file for role based button display.
* None
* Login as adminitrator, site builder or developer and notice that these roles have access to get started button.
* Login as other user roles apart from above and they don't have access to button.
> ACMS-1094: Added conditions in twig file for role based button display.

- DEVELOPING.md
**Motivation**
* The backstop tests are failing on cloud IDE because of the host related error. We need to update documentation to be able to resolve the error on cloud IDE.
Fixes #NNN
* Update the documentation - "DEVELOPING.md" with steps to resolve the host related error.
* None
* Add trusted host pattern for localhost
* RUn the tests again on cloud IDE
* Notice that there are no host related issues post adding the host pattern on cloud IDE.
> ACMS-811: Added the documentation for resolving the host error on cloud IDE.

- grumphp.yml
- modules/acquia_cms_common/src/Services/AcmsUtilityService.php
- modules/acquia_cms_image/acquia_cms_image.install
- modules/acquia_cms_place/tests/src/Functional/PlaceTest.php
- modules/acquia_cms_tour/tests/src/Functional/GetStartedButtonTest.php
- tests/src/ExistingSite/LoginRedirectionTest.php
**Motivation**
Fixes all PHPCS errors/warnings which was appearing earlier.
- Ran phpcbf command to automatically fix most of the errors/warnings.
- Fixed some PHPCS errors/warnings manually.
- Change the twigcs rulset from: `Allocine\Twigcs\Ruleset\Official` to `FriendsOfTwig\Twigcs\Ruleset\Official`
N/A
Run command i.e `./vendor/bin/grumphp run` and you shouldn't see any error/warning.
> ACMS-1114: Fixed all PHPCS errors & warnings.

- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-1102](https://backlog.acquia.com/browse/ACMS-1102)
Update Drupal core to 9.3.9
NA
Login to https://orionacmsdev.prod.acquia-sites.com/ as administrator
Head towards /admin/reports/updates
Verify Drupal core is updated to 9.3.9
> ACMS-1102: Upgrade drupal to 9.3.9

- .gitignore
- composer.json
- composer.lock
- modules/acquia_cms_headless/acquia_cms_headless.info.yml
- modules/acquia_cms_headless/acquia_cms_headless.install
- modules/acquia_cms_headless/acquia_cms_headless.permissions.yml
- modules/acquia_cms_headless/composer.json
_Submitted on behalf of @emb03_
**Motivation**
Fixes [1070](https://github.com/acquia/acquia_cms/issues/1070)
- Adds headless submodule
- Adds drupal/next to acquia_cms composer.
none
> ACMS-1070: Adds Nextjs to ACMS Headless module.

- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-1139](https://backlog.acquia.com/browse/ACMS-1139)
Update Drupal contrib modules to latest
- GoogleTagManager 8.x-1.4 - Recommended version:8.x-1.5 (2022-Mar-29)
- Moderation Sidebar 8.x-1.4 - Recommended version:8.x-1.5 (2022-Mar-24)
- Reroute Email 2.1.0 - Recommended version:2.1.1 (2022-Mar-29)
NA
- login to https://orionacmsdev.prod.acquia-sites.com/ as admin
- head towards /admin/reports/updates
- listed modules should be updated to latest
> ACMS-1139: Drupal contrib module updates

- modules/acquia_cms_site_studio/src/Plugin/AcquiaCmsTour/SiteStudioCoreForm.php
- modules/acquia_cms_tour/src/Form/InstallationWizardForm.php
- modules/acquia_cms_tour/src/Plugin/AcquiaCmsTour/GoogleAnalyticsForm.php
**Motivation**
Fixes #[ACMS-1152](https://backlog.acquia.com/browse/ACMS-1152)
Fix application down error when google analytics is the last item in the tour wizard.
NA
- Install Vanilla Drupal application with:
- google_analytics
- acquia_cms_tour
- enable both modules listed above
- Head towards /admin/tour/dashboard
- Click on Wizard set-up
- You should see pop-up with Google Analytics config form
- Click on Skip this step
- You should see the status message(The configuration options have been saved.) and application should not be down 
> ACMS-1152: Making google analytics as last item in the wizard gives error

- tests/packages_alter.yml
**Motivation**
Cog has been dead and unmaintained for a while (possibly years). It was removed from ORCA last year, so there's no need to remove it yourself via packages_alter: https://github.com/acquia/orca/pull/168
Remove Cog from packages_alter
> Remove references to Cog

- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-1183](https://backlog.acquia.com/browse/ACMS-1183)
Add patch in root composer.json file for google_analytics.
NA
- Install acquia_cms
- `composer create-project acquia/drupal-recommended-project`
- `cd /drupal-recommended-project`
- `composer acms:install`
- `drush cex`
- Export configs
- `drush cex`
- Install acquia_cms using existing config
- `drush site:install --account-pass admin --existing-config`
- Site should install without any error
> ACMS-1183: Site install with existing configuration gives error

- acquia_cms.info.yml
**Motivation**
Fixes #[ACMS-1190](https://backlog.acquia.com/browse/ACMS-1190)
- When Downloading Acquia CMS page module, it shouldn't download Acquia CMS Site Studio module.
- User should be able to install & enable module Acquia CMS page without enabling Acquia CMS Site Studio module.
- When Acquia CMS page module is installed user should see the new content type i.e page.
- Following should happen when Acquia CMS Site Studio module is not installed, when enabling Acquia CMS Page module:
- User shouldn't see layout canvas field on Page content type.
- The Search Description field should be labelled as Body.
- Following should happen when Acquia CMS Site Studio module is already enabled, when enabling Acquia CMS Page module:
- User should see layout canvas field on …
> ACMS-1190: Decouple Acquia CMS Page module.

- modules/acquia_cms_article/acquia_cms_article.install
- modules/acquia_cms_article/config/optional/pathauto.pattern.article.yml
- modules/acquia_cms_event/acquia_cms_event.install
- modules/acquia_cms_event/config/optional/pathauto.pattern.event_path.yml
- modules/acquia_cms_page/acquia_cms_page.install
- modules/acquia_cms_page/config/optional/pathauto.pattern.page.yml
- modules/acquia_cms_person/acquia_cms_person.install
- modules/acquia_cms_person/config/optional/pathauto.pattern.person.yml
- modules/acquia_cms_place/acquia_cms_place.install
- modules/acquia_cms_place/config/optional/pathauto.pattern.place_path.yml
- tests/travis/install.sh
**Motivation**
* The site installation is breaking due to pathauto config containing the "node" deprecated bundle.
Fixes #NNN
* Remove deprecated "node" bundle, update the config file.
* Added update hook for the same.
* None
* Switch to branch ACMS-1332 on local and run command - "./bin/acms acms:install"
* Notice that installation completes without any issues.
**Testing Screenshots**
> ACMS-1332: Updated the config pauthauto pattern files and added update hooks

- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.module
**Motivation**
Fixes (https://backlog.acquia.com/browse/ACMS-1328)
$link parent is not checked for isset condition
When travis job is run this error should be fixed when we install starter kit
> ACMS-1328: Fixed warning errors for acquia cms headless module

- modules/acquia_cms_headless/composer.json
- modules/acquia_cms_headless/drush.services.yml
- modules/acquia_cms_headless/src/Commands/AcquiaCmsHeadlessCommands.php
- modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
- modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php
**Motivation**
Fixes #[ACMS-1337](https://backlog.acquia.com/browse/ACMS-1337)
Create a new drush command with name: drush acms:headless:init having following options:
--site-url: Required.
--site-name: Required.
--env-file: Optional.
Create a new drush command with name: drush acms:headless:regenerate-env having following options/arguments:
--site-url: Optional 
--env-file: Optional.
NA
- vendor/bin/acms site:install --yes --account-pass admin
- vendor/bin/drush en acquia_cms_headless_ui
- vendor/bin/drush acms:headless:new-nextjs  --site-url='http://localhost:3000' --site-name='Headless site one' --env-file='../frontend/.env.local' --uri http://acms.dev.local/
- vendor/bin/drush acms:headless:regenerate-env …
> ACMS-1337: Drush commands for Nextjs environment variables.

- modules/acquia_cms_site_studio/composer.json
**Motivation**
Fixes #ACMS-1360
Update site studio to 6.9.1
PHP Unit test related to site studio i.e. [SiteStudioCoreTest::testSiteStudioCore](https://github.com/acquia/acquia_cms/blob/feature/new-site-studio/modules/acquia_cms_site_studio/tests/src/Functional/SiteStudioCoreTest.php) will fail and taken care in ACMS-1330.
- Install site with this branch use `./vendor/bin/acms site:install`
- enable starter module `drush in acquia_cms_starter`
- test everything works fine
> ACMS-1360: Update Site Studio to 6.9.1

- modules/acquia_cms_headless/acquia_cms_headless.module
- modules/acquia_cms_headless/composer.json
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.module
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.services.yml
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Routing/SitePreviewRouteSubscriber.php
**Motivation**
* To remove the re-direction code from acquia_cms_headless module and move to acquia_cms_headless_ui module.
* To re-write the redirection logic to work only when destination params are not set.
* Loom recording - https://www.loom.com/share/8fc6be4203a6428c97c4f98d1b97bb39
Fixes #NNN
* To remove the re-direction code from acquia_cms_headless module and move to acquia_cms_headless_ui module.
* To re-write the redirection logic to work only when destination params are not set.
* None
* Enable headless mode and head towards - /admin/content page.
* Edit any node and notice that node edit URL has the destination query params ex. `?destination=/acquia_cms/admin/content`
* Make changes and notice that the user is …
> ACMS-1312: Revamped the redirection code for site preview.

- modules/acquia_cms_search/acquia_cms_search.module
- modules/acquia_cms_search/src/Facade/AcquiaSearchFacade.php
- modules/acquia_cms_search/src/Plugin/AcquiaCmsTour/AcquiaSearchForm.php
**Motivation**
Fixes #ACMS-1363
Acquia Solr Search should work out of the box when enabled, and database server should be disabled.
NA
- install site with this code
- login into application as admin
- head towards /admin/tour/dashboard
- click on Acquia Search accordion 
- provide valid input to all fields
- click on save
- head towards /admin/config/search/search-api
- see Acquia Search Solr Index, Database Search Server should be disabled
- head towards /admin/config/search/search-api/index/content
- check index status
> ACMS-1363: Acquia Solr Search should work out of the box when enabled

- modules/acquia_cms_headless/README.md
- modules/acquia_cms_headless/src/Commands/AcquiaCmsHeadlessCommands.php
- modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
- modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php
We are aiming to achieve the following - 
* Check if the oauth_keys directory path is set in Settings.php file of the project. If set, then accept that path as it is.
* Also add instructions for setting the directory path in settings.php in the README.md file of acquia_cms_headless module.
* Check if directory at path provided in settings.php file is writable or not, if not - then log the error using Drupal logger
* Check if file already exist in the above mentioned path, then overwrite if already exists.
* If path does is not mentioned in settings.php & also the environment in not the Acquia Environment then pick up path already mentioned in StarterkitNextjsService.php file line no. 393 
{noformat}
$dir = "../oauth_keys/$site_path[0]/$site_path[1]";
{noformat}
* Lastly, If environment is …
> ACMS-1252: Added the logic to fetch the directory location.

- modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
- modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php
**Motivation**
Fixes #ACMS-1368
Check the checkbox if nextjs starterkit installed.
Install headless starterkit opt for nextjs via CLI, drush and UI
> ACMS-1368: Auto checking the checkbox for enable nextjs starterkit.

- modules/acquia_cms_starter/modules/acquia_cms_site_studio_content/content/node/d513a098-2322-4f8a-b61f-58d986cd4197.yml
**Motivation**
* The home page default is not working for low code starter kit installation
Fixes #NNN
* Fixed the home page for low code installation.
* None
* Install site using starterkit - low code, community or headless and notice that home page shows up correctly for all three starter kits.
> ACMS-1218: Updated the pathauto settings for default frontpage.

- modules/acquia_cms_headless/src/Commands/AcquiaCmsHeadlessCommands.php
**Motivation**
Fixes #[ACMS-1377](https://backlog.acquia.com/browse/ACMS-1377)
The drush command acms:headless:new-nextjs places the .env file relative to the Drupal docroot. This is not well understand from the acms starterkit wizard and is difficult to find after the starterkit has completed.
NA
./vendor/bin/acms acms:install acquia_cms_headless
Answer yes to use next.js starterkit
Provide name for env-file argument
> ACMS-1377: node.js env-file in Drupal docroot.

- modules/acquia_cms_common/acquia_cms_common.install
- modules/acquia_cms_common/src/Services/ToggleModulesService.php
**Motivation**
* Syslog Module should be enabled based on different environments.
Fixes #NNN
* Managed the conditions for enabling the syslog module on different environments.
* None
* Install site using command - `vendor/bin/drush site:install minimal --account-pass admin -vvv`
* Once the site is installed, run the command - `vendor/bin/drush acms:toggle:modules` and verify that syslog module is enabled / disabled according to the criteria mentioned in the [ticket](https://backlog.acquia.com/browse/ACMS-1378).
Test 2
* Install site using `vendor/bin/acms acms:install` command.
* Visit site & notice that syslog module enablement/disablement is handled on it's own according to the environment installed on.
**Merge …
> ACMS-1378: Added code to enable syslog module on IDE env.

- modules/acquia_cms_common/src/Traits/PasswordGeneratorTrait.php
- modules/acquia_cms_headless/src/Service/StarterkitNextjsService.php
**Motivation**
* Updated the password generation for Headless Consumer & Preview Secret
Fixes #NNN
* Updated the password generation for Headless Consumer & Preview Secret
* Associated PR - https://github.com/acquia/acquia-cms-starterkit/pull/58
* None
* Run site install using acquia_cms_headless installation and notice that consumer & preview secret are password compliant.
**Example Screenshot**
> ACMS-1393: Added the required php generator password file.

- modules/acquia_cms_page/acquia_cms_page.install
- modules/acquia_cms_page/config/optional/node.type.page.yml
- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
- modules/acquia_cms_site_studio/acquia_cms_site_studio.module
**Motivation**
Fixes #ACMS-1380
- Remove node_revision_delete config from acquia_cms_page/config/optional/node.type.page.yml
- Add update hook to remove node_revision_delete config from node.type.page
NA
**New site:**
- Install acquia_cms_page, node_revision_delete config shouldn't be there 
- Install acquia_cms_site_studio, node_revision_delete third party config must be available
- Follow 2 and 3 in reverse manner with new install
- Verify site working fine
**Existing site:**
- Upgrade codebase this branch
- Execute `drush updb`
- Now execute `drush cex` so node_revision_delete does not exist in your exported configs
- Now execute `drush cim`
- Verify site working fine
**Merge …
> ACMS-1380: Removed node_revision_delete config from node.type.page

- modules/acquia_cms_headless/acquia_cms_headless.services.yml
- modules/acquia_cms_headless/src/Access/PreviewLinkAccessCheck.php
- modules/acquia_cms_headless/src/Routing/PreviewLinkRouteSubscriber.php
**Motivation**
* The preview button shows up for the anonymous user as well. It should only show up for authenticated user (logged in) who have access to content edit or update or create.
Fixes #[ACMS-1408](https://backlog.acquia.com/browse/ACMS-1408)
* The preview button shows up for the anonymous user as well. It should only show up for authenticated user (logged in) who have access to content edit or update or create.
* None
* Install the acquia_cms_headless starter kit and access the site as anonymous user.
* Notice that the "Preview" link is no longer accessible.
> ACMS-1408: Added access check for content to show preview link.

- modules/acquia_cms_headless/acquia_cms_headless.module
**Motivation**
Fixes #ACMS-1453
Updated logic to assign all roles to headless user after role refactor.
NA
- Enable below module combination for testing
-- acquia_cms_headless
-- acquia_cms_headless then acquia_cms_starter or any content model module
-- acquia_cms_starter or any content model module then acquia_cms_headless
- Enable pure headless mode 
- Head towards /admin/tour/dashboard
- Click on Headless
- Check Enable headless mode
- Click on save
- Head towards /admin/access/users
- Verify all roles assigned to Headless user
> ACMS-1453: Update logic to assign all roles to headless user after role refactor.

- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Service/PureHeadlessModeInstallHandler.php
- modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
**Motivation**
Fixes #ACMS-1454
- Nextjs twice consumer data from tour dashboard should not new nextjs if checkbox is already checked.
- Pure headless mode switcher should be checked if only acquia_cms_headless_ui is installed & enabled.
- install headless + nextjs
- Install healdess+demo content
- Enable nextJs starter kit via tour dashboard
- Enable Headless mode from tour dashboard.
> ACMS-1454: Resolve headless mode switcher for pure headless.

- modules/acquia_cms_dam/acquia_cms_dam.info.yml
- modules/acquia_cms_dam/composer.json
**Motivation**
Fixes #ACMS-1470
Require and install ACMS image and video module when installing ACMS DAM
NA
- Checkout this branch
- Execute composer update
- Verify acquia_cms_image and acquia_cms_video modules are downloaded
- Execute drush in acquia_cms_dam -y
- Verify acquia_cms_image, acquia_cms_video modules installed
- Verify site working fine.
> ACMS-1470: Add Acquia CMS Image and Video dependency in Acquia CMS DAM.

- composer.lock
- modules/acquia_cms_common/composer.json
**Motivation**
Fixes #ACMS-1511
Updated Acquia content hub to use `2 || 3` latest version
NA
- Use this branch.
- Execute composer update.
- Acquia content hub should be updated to latest version.
- Verify site.
> ACMS-1511: Upgrade Acquia Content Hub to latest version.

- modules/acquia_cms_search/composer.json
- modules/acquia_cms_tour/src/Form/StarterKitSelectionWizardForm.php
- modules/acquia_cms_tour/src/Plugin/AcquiaCmsStarterKit/StarterKitConfigForm.php
- modules/acquia_cms_tour/src/Services/StarterKitService.php
**Motivation**
Fixes #ACMS-1272
Enable modules in batch when enabling via UI using starterkit.
NA
- Use this branch.
- Install site `drush si minimal`
- Install tour module `drush in acquia_cms_tour`
- Login into application and head towards `/admin/tour/dashboard`
- Click on `Starter kit set-up`
- Select starter kit click on next
- Select Demo content or content model click on complete
- It should start batch and install modules
- Verify site working fine, all modules installed successfully.
> ACMS-1272: Enable modules in a batch when enabling starter kits via Cloud UI and Site Factory UI

- modules/acquia_cms_common/acquia_cms_common.services.yml
- modules/acquia_cms_common/src/AcmsModulesUninstallValidator.php
**Motivation**
Fixes #ACMS-1500
Validate site studio packages deleted before uninstalling the module.
NA
- Install site with this code
- Install site studio module import packages
- Now try to uninstall any module having site studio package.
- It should give warning.
- Verify site.
> ACMS-1500: Added modules uninstall validator for site studio packages.

- modules/acquia_cms_site_studio/composer.json
**Motivation**
Fixes ACMS-1555
Update the patch to fix the null deprecations warnings.
- Add a page content type
- Add a component from site studio.
> ACMS-1555: Fixing null deprecations for site studio 6.9.x

- modules/acquia_cms_common/composer.json
**Motivation**
Fixes #ACMS-1590
added nnnick/chartjs library requirement in acquia_cms_common modules composer.json file.
NA
- checkout ACMS-1590 branch
- execute composer install command
- verify that nnnick/chartjs library is getting downloaded and present in docroot/librarie.
> ACMS-1590: ACMS D10 Regression testing - Isolated Test - chartjs library not found issue fix.

- modules/acquia_cms_common/composer.json
- modules/acquia_cms_site_studio/config/pack_acquia_cms_core/cohesion_custom_styles.cohesion_custom_style.b2c36087.yml
**Motivation**
Fixes #ACMS-1420
updated entity update hook in site studio config to support 6.9 and 7.0
NA
Install site with this branch and verify it works with site studio 6.9 and 7.0 both versions.
> ACMS-1420: Updated entity update hook for site studio custom style to support 6.9 and 7.0

- tests/src/ExistingSiteJavascript/CohesionComponentTestBase.php
- tests/src/ExistingSiteJavascript/CohesionHelperTestBase.php
- tests/src/ExistingSiteJavascript/LinkedFeatureCardComponentTest.php
**Motivation**
Fixes #ACMS-1516
Revert commented test for Linked Feature Card Component in existing tests.
Currently existing site tests are failing because of the cohesion module Drupal 10 compatibility issues.
- Install site with site studio and import packages
- Execute ./acms-run-test.sh
- verify that "Link to page or URL" asserting is passing
> ACMS-1516: Fix failing CI test for LinkedFeatureCardComponentTest

- modules/acquia_cms_tour/acquia_cms_tour.libraries.yml
- modules/acquia_cms_tour/js/acquia_cms_tour_dashboard.js
**Motivation**
Fixes #ACMS-1641
> ACMS-1641: Remove deprecated jquery.once from acquia_cms_tour module.

- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/tests/src/Functional/HeadlessFrontpageTest.php
- modules/acquia_cms_headless/tests/src/Functional/HeadlessBrowserTestBase.php
Motivation
Fixes https://github.com/acquia/acquia_cms/pull/1287
Proposed changes
Added test cases for headless installation frontpage checks. The test case checks for the following -
Frontpage is login when user is not authenticated.
Frontpage is content admin page when user logged in with admin.
Frontpage theme is admin theme.
> ACMS-1480: acquia_cms_headless: PHPUnit testcases for Frontpage

- composer.lock
- modules/acquia_cms_headless/composer.json
**Motivation**
Fixes #[ACMS-1643](https://backlog.acquia.com/browse/ACMS-1643)
> ACMS-1643: Replace Gist with drupal.org URL from ACMS Headless.

- composer.json
- composer.lock
Temporary pinning the php-http/discovery library as it's causing CI to fail.
Pinn the library `php-http/discovery` to previous working version.
N/A
> ACMS-1661: Temporary pinning the php-http/discovery library as it's CI is failing with latest release.

- modules/acquia_cms_common/modules/acquia_cms_development/config/rewrite/search_api.index.acquia_search_index.yml
- modules/acquia_cms_common/modules/acquia_cms_development/config/rewrite/views.view.acquia_search.yml
**Motivation**
Fixes  Hotfix as per release of https://www.drupal.org/project/acquia_search/releases/3.1.6
> ACMS-0000: Hotfix for backstop CI failure cause of search module.

- modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationFromTourPageTest.php
- modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationTest.php
**Motivation**
Fixes #ACMS-1707 - this is hotfix to stop CI failure.
Commented the test in [AcquiaSearchIntegrationFromTourPageTest.php](https://github.com/acquia/acquia_cms/blob/develop/modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationFromTourPageTest.php#L85-L89) and [AcquiaSearchIntegrationTest.php ](https://github.com/acquia/acquia_cms/blob/develop/modules/acquia_cms_search/tests/src/Functional/AcquiaSearchIntegrationTest.php#L56-L60)
NA
> ACMS-1424: Fix Acquia CMS search module tests are failure due to acquia_search 3.1.6 release.

- composer.json
- composer.lock
Fixes: [ACMS-1677](https://backlog.acquia.com/browse/ACMS-1677)
Moving dependencies from Contrib to ACMS modules.
NA
Install site with ACMS-1677 branch. 
`git checkout ACMS-1677-1.5.x`
`composer install`
Installation site with minimal profile and Acquia CMS module.
` drush si acquia_cms --account-pass=admin `
Verify site working fine.
_**Note: pin acquia_search to 3.1.5 till ACMS-1707 get released.**_
> ACMS-1677: Moving dependencies from Contrib to ACMS modules.

- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-1748](https://backlog.acquia.com/browse/ACMS-1748)
Fix failing CI jobs due to the recent change in chartjs library.
NA
> ACMS-1748: Fix Chart Js Library failing ACMS CI jobs.

- composer.json
- composer.lock
- modules/acquia_cms_headless/composer.json
- modules/acquia_cms_headless/tests/src/Functional/HeadlessSubrequestsTest.php
**Motivation**
Fixes #ACMS-1489
PHPUnit testcase for headless subrequests functionality.
NA
Verify Acquia CMS Headless test passing in CI
> ACMS-1489: PHPUnit testcases for headless subrequests functionality.

- composer.json
- composer.lock
**Motivation**
Fixes #ACMS-1820
Remove patches as Acquia DAM module 1.0.7 released.
NA
Composer should install Acquia CMS DAM dependency without error/warning.
> ACMS-1820: Remove patches as Acquia DAM module 1.0.7 released.

- acquia_cms.info.yml
- composer.json
- tests/ci/install.sh
**Motivation**
Fixes #ACMS-1746
Moved contrib modules from ACMS common to ACMS module:
acquia_search, google_analytics, google_tag, honeypot, recaptcha, reroute_email, shield, nnnick/chartjs
NA
CI should Pass
> Feature/moving dependencies 2.x

- modules/acquia_cms_headless/tests/src/Functional/DashboardNextjsSitesTest.php
- modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
- modules/acquia_cms_site_studio/acquia_cms_site_studio.module
- modules/acquia_cms_site_studio/config/install/user.role.developer.yml
- modules/acquia_cms_site_studio/src/Helper/SiteStudioPermissionHelper.php
**Motivation**
the module is not actively being used by Acquia CMS users should be able to uninstall it if they don't need it.
> ACMS-1816: Acquia CMS should not install Site Studio Style Guide Manager if it's not using it

- modules/acquia_cms_headless/acquia_cms_headless.services.yml
- modules/acquia_cms_headless/src/Config/AcquiaCmsHeadlessConfigSubscriber.php
**Motivation**
Fixes #ACMS-1730
Config event to create user on config import.
NA
Verify headless user creation on config import.
- Use ACMS-1730 branch to install site using `./vendor/bin/drush si minimal --account-pass=admin`
- Install ACMS headless module `./vendor/bin/drush in acquia_cms_headless -y`
- Export config `./vendor/bin/drush cex -y`
- Copy uuid using `./vendor/bin/drush cget system.site uuid` then copy the ID from output
- Install site `./vendor/bin/drush si minimal --account-pass=admin`
- Set site uuid `./vendor/bin/drush cset system.site uuid <copied uuid>`
- Import config `./vendor/bin/drush cim -y && ./vendor/bin/drush cr && ./vendor/bin/drush cim -y`
- Verify Headless user created after cim
**Merge …
> ACMS-1730: add config event to create user on config import.

- modules/acquia_cms_common/modules/acquia_cms_support/src/Controller/AcquiaCmsConfigSyncOverridden.php
**Motivation**
Fixes #ACMS-617
Report only enabled modules config difference.
NA
- Clone ACMS-617 branch.
- install site and enable acquia_cms_support module
- visit `admin/config/development/acquia-cms-support/overridden-config` and verify if module is enabled for any config which is shown.
- install any acquia_cms module and verify the above scenario again.
> ACMS-617: Report only enabled modules config difference.

- modules/acquia_cms_common/acquia_cms_common.services.yml
- modules/acquia_cms_common/src/EventSubscriber/KernelTerminate/AcquiaCmsTelemetry.php
- modules/acquia_cms_common/tests/src/Kernel/AcquiaCmsTelemetryTest.php
**Motivation**
ACMS-1597: Send Acquia CMS telemetry data..
> ACMS-1597: Send telemetry data.

- acquia_cms.info.yml
- composer.json
**Motivation**
Fixes #ACMS-1843
- Update Google Tag to support 1.x and 2.x version.
- Remove google analytics from module dependency list.
NA
> ACMS-1843: Update Google Tag to support 1.x and 2.x version.

- composer.lock
**Motivation**
Fixes #ACMS1903
Downgrade Drush to 11 as Drush 12 is not supported on cloud.
NA
- Deploy **pipelines-build-ACMS-1903-drush-11** branch on cloud 
- verify everything working fine
> ACMS-1903: downgrade drush to 11 as drush 12 is not supported on cloud.

- composer.lock
- modules/acquia_cms_search/composer.json
- modules/acquia_cms_site_studio/composer.json
- tests/ci/install.sh
**Motivation**
Fixes #[ACMS-1729](https://backlog.acquia.com/browse/ACMS-1729)
Fix failing ExistingSiteJavascript test in CI.
Pin collapsiblock to version 4.0.0
- Checkout this branch and run composer install
- Install site with site studio key present
- Run test tests/src/ExistingSiteJavascript/SearchTest.php and you will see the failure.
> ACMS-1729: Fix failing ExistingSiteJavascript test in CI.

- acquia_cms.profile
**Motivation**
Fixes #ACMS-1905
Track Acquia CMS Starterkits in telemetry data.
NA
> ACMS-1905: Track Acquia CMS Starterkits in telemetry data.

- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.module
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.routing.yml
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Service/PureHeadlessModeInstallHandler.php
- modules/acquia_cms_headless/tests/src/Functional/PureHeadlessModeMenuTest.php
**Motivation**
Fixes #[ACMS-1922](https://backlog.acquia.com/browse/ACMS-1922)
Keep core below 10.1
- Setup site with headless starterkit
- Enable block_content module
- Visit /admin/content-models page
- You should see the error.
> ACMS-1922: Issue with block_content and Acquia CMS Headless.

- .github/workflows/acquia_cms_ci.workflow.yml
- composer.lock
- modules/acquia_cms_common/composer.json
**Motivation**
Fixes #ACMS-1947
Remove redirect patch as it merged and released in latest version 1.9.
NA
> ACMS-1947: Remove redirect patch as it merged and released in latest version 1.9.

- acquia_cms.profile
**Motivation**
Fixes #[ACMS-1944](https://backlog.acquia.com/browse/ACMS-1944)
Fix Too few arguments to function cohesion_sync_modules_installed issue.
NA
follow from ticket
> ACMS-1944: Fix Too few arguments to function cohesion_sync_modules_installed issue.

- composer.lock
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_toolbar/composer.json
**Motivation**
Fixes #[ACMS-1919](https://backlog.acquia.com/browse/ACMS-1919)
Fix Toolbar does not indicate active menu trail for pages not included in Toolbar.
NA
> ACMS-1919: Fix Toolbar does not indicate active menu trail for pages not included in Toolbar.

- .github/workflows/acquia_cms_ci.workflow.yml
- composer.json
- composer.lock
- modules/acquia_cms_component/composer.json
- modules/acquia_cms_headless/composer.json
**Motivation**
Fixes #[ACMS-1960](https://backlog.acquia.com/browse/ACMS-1960)
Remove JSONAPI Extras patch as it is failing with latest version 3.24.
NA
> ACMS-1960: Remove JSONAPI Extras patch as it is failing with latest version 3.24.

- composer.lock
- modules/acquia_cms_common/composer.json
**Motivation**
Fixes #[ACMS-1918](https://backlog.acquia.com/browse/ACMS-1918)
1. Few of the test participants navigated to edit fields of an incorrect bundle or even incorrect entity type. When asked, they thought they were editing the entity type or bundle we instructed them to edit. Without knowing the content model of the site, the only indication in the UI that this is not the case is in the breadcrumb
2. Users don't always understand what's the context for the tabs (especially problematic for the second level). For example, on Manage Display there are "Default" and "Teaser" tabs, and users didn't realize they were view modes.
NA
- Checkout [ACMS-1918](https://backlog.acquia.com/browse/ACMS-1918)
- Run composer …
> ACMS-1918: Page title should contextualize the local navigation.

- modules/acquia_cms_search/acquia_cms_search.module
- modules/acquia_cms_search/src/Facade/SearchFacade.php
**Motivation**
Fixes #[ACMS-1945](https://backlog.acquia.com/browse/ACMS-1945)
Provide options to add field to the search index automatically.
We can add field to search index manually.
Checkout code to this branch
- Install site with community starter kit
- Select yes for content model
- Login to site as admin user
- Add new field to article content type
- On the field configuration page, check the box "Add field to search index"
- Verify the content index, this field should be available.
> ACMS-1945: New fields not added to the search index automatically

- modules/acquia_cms_common/tests/src/ExistingSite/ContentTypeListTestBase.php
- modules/acquia_cms_search/acquia_cms_search.module
- modules/acquia_cms_search/tests/src/FunctionalJavascript/AcquiaFacetSearchTest.php
- tests/src/ExistingSiteJavascript/SearchTest.php
**Motivation**
Fixes ACMS-1972
Field storage and settings page throws error with new core improvement patches.
> ACMS-1972: Fixing new search index field on field settings and storage page.

- acquia_cms.info.yml
**Motivation**
Fixes #[ACMS-1991](https://acquia.atlassian.net/browse/ACMS-1991)
Remove purge_processor_lateruntime install dependency from Acquia CMS profile.
NA
- Create project using `composer create-project acquia/drupal-recommended-project:^1 acquia_cms && cd acquia_cms`
- Require Acquia CMS profile using `composer require acquia/acquia_cms:^1.5`
- Update Acquia CMS Common to 2.1.4 or older using `composer update drupal/acquia_cms_common:2.1.4`
- Install site using `./vendor/bin/drush si acquia_cms`
- Update Acquia CMS Common to latest or version greater than 2.1.4 using `composer update drupal/acquia_cms_common:^2.1.5`
- Update database using `./vendor/bin/drush updb` & you will encounter the error.
- Update Acquia …
> ACMS-1991: Fix Acquia CMS Common and Acquia CMS profile conflict.

- composer.json
- composer.lock
- modules/acquia_cms_common/acquia_cms_common.install
- modules/acquia_cms_common/acquia_cms_common.module
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Service/PureHeadlessModeInstallHandler.php
- modules/acquia_cms_headless/tests/src/Functional/HeadlessContentTest.php
- modules/acquia_cms_headless/tests/src/Functional/HeadlessModeEnablementTest.php
- modules/acquia_cms_headless/tests/src/Functional/PureHeadlessModeMenuTest.php
- modules/acquia_cms_tour/src/Services/StarterKitService.php
- tests/src/ExistingSite/InstallStateTest.php
- tests/src/ExistingSiteJavascript/CohesionTestBase.php
- tests/src/ExistingSiteJavascript/EntityCloneIntegrationTest.php
**Motivation**
Fixes #[ACMS-1989](https://acquia.atlassian.net/browse/ACMS-1989)
This PR is created to check if there any test failure with Gin theme.
This can be closed without any further action once the issue identification is completed, or it can be used, and further changes can be made here directly.
NA
> ACMS-1989: Update admin theme in Acquia CMS to Gin.

- composer.lock
- modules/acquia_cms_place/composer.json
Remove Geocoder patch from Acquia CMS Place
**Motivation**
This will solve failing ACMS Installation
Remove geocoder patch
> ACMS-2006: Remove failing Geocoder patch as released in 3.35 and 4.10 version.

- acquia_cms.module
- composer.json
**Motivation**
Fixes #[ACMS-2007](https://acquia.atlassian.net/browse/ACMS-2007)
Remove duplicate code from Acquia CMS module as available in Acquia CMS Common module.
NA
> ACMS-2007: Remove duplicate code from Acquia CMS as available in Acquia CMS Common module.

- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/acquia_cms_headless_ui.module
- modules/acquia_cms_headless/modules/acquia_cms_headless_ui/src/Menu/ViewJsonTask.php
**Motivation**
Fixes #ACMS-1984
Excluding view json task for users, as we dont see json data for users since 9.3
Follow steps from ticket
> ACMS-1984: Moderation dashboard fix for users.

- composer.json
- composer.lock
- modules/acquia_cms_common/acquia_cms_common.install
- modules/acquia_cms_common/composer.json
**Motivation**
Fixes #ACMS-1986
Include gin theme in ACMS Common module.
NA
- Clone acquia/acquia_cms repository using `git clone -b ACMS-2007 git@github.com:acquia/acquia_cms.git acquia_cms_common && cd acquia_cms_common`
- Install dependencies using `composer install`
- Verify that gin theme is downloaded.
- Install site using `./vendor/bin/drush si minimal`
- Install Acquia CMS Common module using `./vendor/bin/drush in acquia_cms_common -y`
- Verify that gin is set as admin theme.
> ACMS-1986: Add gin theme in Acquia CMS Common module.

- modules/acquia_cms_search/config/pack_acquia_cms_search/cohesion_templates.cohesion_view_templates.view_tpl_search_fallback.yml
**Motivation**
Fixes #ACMS-1636
Fixes fallback view for search
git clone develop
install site using acquia_cms_enterprise_low_code and set fallback view using commands
./vendor/bin/drush cset views.view.search display.default.display_options.empty.view_fallback.simulate_unavailable TRUE
go to site and search something and see fallback is broken including pagination.
git checkout ACMS-1636
./vendor/bin/drush cset views.view.search display.default.display_options.empty.view_fallback.simulate_unavailable TRUE
now check fallback is working fine.
**For existing users**
- Go to the website and navigate to the "/user/login" page.
- Enter the admin credentials to log in.
- Once logged in, go to the …
> ACMS-1636: View Search Fallback is broken on ACMS install.

- composer.lock
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_common/src/Facade/SitemapFacade.php
**Motivation**
Fixes #[ACMS-3337](https://acquia.atlassian.net/browse/ACMS-3337)
Update Simple Sitemap facade as per latest version(i.e. 4.1.7).
NA
> ACMS-3337: Fix Simple Sitemap 4.1.7 version breaks site install.

- DEVELOPING.md
- acms-run-tests.sh
- acms/build.yml
- acquia_cms.module
- composer.json
- composer.lock
- scripts/acms-split.sh
**Motivation**
Update scripts and installation hooks to gin theme as admin theme.
-  Removed all references for acquia_claro.
- Included gin modules/theme dependencies.
N/A
- Run command `./vendor/bin/acms site:install --yes` and site installation should work as expected, setting gin theme & enable gin modules.
> ACMS-2008: Update scripts and installation hooks to gin theme as admin theme.

- composer.lock
- modules/acquia_cms_site_studio/composer.json
- modules/sitestudio_config_management/composer.json
**Motivation**
Fixes #[ACMS-3359](https://acquia.atlassian.net/browse/ACMS-3359)
Restrict Site Studio to <7.4 version.
NA
- Checkout branch ACMS-3359
- Install dependencies using `composer install`
- Verify site studio version is less than 7.4.
> ACMS-3359: Restrict Site Studio to <7.4 version.

- composer.lock
- modules/acquia_cms_common/composer.json
**Motivation**
Fixes #[3354](https://acquia.atlassian.net/browse/ACMS-3354)
Remove Drupal core patches as available in 10.2.x core.
NA
- Checkout branch ACMS-3354-1
- Install dependencies using `composer install`
- Try to update drupal core to 10.2.x
- Verify it is not allowing to update
- Verify patches applied successfully.
> ACMS-3354: Ristrict ACMS Common 3.3.x to drupal core 10.1.x version.

- .github/workflows/acquia_cms_ci.workflow.yml
- .github/workflows/acquia_cms_cron.yml
- acms-run-tests.sh
- composer.lock
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_common/config/rewrite/system.performance.yml
- modules/acquia_cms_tour/src/Form/WelcomeModalForm.php
- tests/src/ExistingSiteJavascript/GoogleMapComponentTest.php
**Motivation**
Fixes #[3354](https://acquia.atlassian.net/browse/ACMS-3354)
Remove Drupal core patches as available in 10.2.x core.
NA
- Checkout branch ACMS-3354
- Install dependencies using `composer install`
- verify patches applied successfully.
> ACMS-3354: Remove 10.2.x DIT patches from Acquia CMS Common module.

- acms/build.yml
- composer.json
- composer.lock
**Motivation**
Fixes #[ACMS-3284](https://acquia.atlassian.net/browse/ACMS-3284)
Update tour styles to work irrespective with any theme.
NA
> ACMS-3284: Update ACMS Tour Dashboard styles.

- modules/acquia_cms_place/composer.json
- modules/acquia_cms_place/tests/src/Functional/PlaceTest.php
**Motivation**
Fixes #ACMS-3469
Added support for Address module version 2.0
No
- git clone acquia_cms
- git checkout ACMS-3469
- ./vendor/bin/acms acms:install 
- install acquia_cms_community
- say yes to demo content
- visit site and check address module version 2.0 is available
> ACMS-3469: Support for the Address module version 2.x.

- composer.lock
- modules/acquia_cms_audio/tests/packages_alter.yml
- modules/acquia_cms_common/.gitlab-ci.yml
- modules/acquia_cms_document/composer.json
- modules/acquia_cms_page/composer.json
- modules/acquia_cms_page/tests/packages_alter.yml
- modules/acquia_cms_page/tests/src/Kernel/PageWithLayoutCanvasFieldTest.php
**Motivation**
Fixes #[ACMS-3657](https://acquia.atlassian.net/browse/ACMS-3657)
Acquia CMS Common: Update GitLab CI pipeline to ignore LATEST_EOL_MAJOR and PREVIOUS_MINOR.
Acquia CMS Page: Add require-dev section in composer.json file to acquia_cms_site_studio. And updated kernelTest to change the order of cohesion_elements module and method return type.
Acquia CMS Document: Add require-dev section in composer.json file to include acquia_claro.
Acquia CMS Audio: Package alter changes to exclude drupal/acquia_contenthub_s3
NA
> ACMS-3657: Update Acquia CMS Ecosystem to make pipeline green.

- modules/acquia_cms_common/acquia_cms_common.install
**Motivation**
Fixes #[ACMS-1987](https://acquia.atlassian.net/browse/ACMS-1987)
Remove GIN theme and GIN toolbar module installation logic from Acquia CMS Common module.
NA
> ACMS-1987: Remove GIN theme and GIN toolbar module installation logic from Acquia CMS Common module.

- modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
**Motivation**
Fixes ACMS-3475
- Moving out contrib modules from .info.yml
- Upgrading node_revision_delete to ^2.0
- Updated the node_revision_delete.settings with latest changes
- Updated tests accordingly
> ACMS-3475: Managing hard dependency of Acquia CMS site studio module.

- composer.json
- composer.lock
- modules/acquia_cms_common/composer.json
- tests/ci/install.sh
**Motivation**
Fixes #ACMS-3560
Requirements
3.0.x
D10 ONLY, dropped support for charts v3 that hasn't had a release since 2022.
update moderation dashboard to version 3.0
> ACMS-3560: Support moderation dashboard major release version 3.x.

- composer.lock
- modules/acquia_cms_common/src/Facade/ConfigHandlerFacade.php
- modules/acquia_cms_common/tests/src/Kernel/ConfigHandlerFacadeTest.php
- modules/acquia_cms_page/acquia_cms_page.install
- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
- modules/acquia_cms_site_studio/acquia_cms_site_studio.module
- modules/acquia_cms_site_studio/composer.json
- modules/acquia_cms_site_studio/tests/src/ExistingSite/NodeRevisionDeleteConfigTest.php
**Motivation**
Fixes ACMS-3650
Update acquia_cms_site_studio composer.json with  2.x version of node revision delete.
> ACMS-3650: Support 2.x version for node revision delete.

- modules/acquia_cms_site_studio/src/Plugin/AcquiaCmsTour/SiteStudioCoreForm.php
- modules/acquia_cms_tour/css/acquia_cms_tour_dashboard.css
**Motivation**
Fixes ACMS-3722
Fix issue for ignoreConfig button error thrown
Overlapping button on tour page is fixed.
> ACMS-3722: Fix ignoreConfig button throws error on sitestudio form over tour page.

- composer.lock
- modules/acquia_cms_search/acquia_cms_search.info.yml
- modules/acquia_cms_search/composer.json
**Motivation**
Fixes ACMS-3476
- Removed patch of search_api
- Support search_api ^1.32 version
- Supports drupal/core: ^10.1 for acquia_cms_search
> ACMS-3746: Upgrading search_api to 1.34 version.

- modules/acquia_cms_headless/src/Plugin/AcquiaCmsTour/AcquiaHeadlessForm.php
- modules/acquia_cms_person/config/optional/views.view.people.yml
- modules/acquia_cms_search/src/Plugin/AcquiaCmsTour/AcquiaConnectorForm.php
- modules/acquia_cms_search/src/Plugin/AcquiaCmsTour/AcquiaSearchForm.php
- modules/acquia_cms_site_studio/src/Plugin/AcquiaCmsTour/SiteStudioCoreForm.php
- modules/acquia_cms_tour/src/Plugin/AcquiaCmsTour/GoogleAnalyticsForm.php
- modules/acquia_cms_tour/src/Plugin/AcquiaCmsTour/GoogleMapsApiForm.php
**Motivation**
Fixes #ACMS-4015
Allow facets to bypass the creation mentioned [here](https://git.drupalcode.org/project/facets/-/blob/3.0.x/src/Entity/Facet.php?ref_type=heads#L1126) with core:10.3 as well and will update all factes configurations later
```
// Register newly created facet within its source, for the caching.
if (($source = $this->getFacetSource()) && $source->getCacheMaxAge() !== 0) {
$source->registerFacet($this);
}
```
> ACMS-4015: The Acquia CMS Search module is causing fatal error on Drupal Core 10.3.x

- composer.json
- composer.lock
- modules/sitestudio_config_management/composer.json
- modules/sitestudio_config_management/sitestudio_config_management.info.yml
**Motivation**
Fixes #ACMS-3947
Drupal 11 compatibility fixes for SiteStudio Config Management.
NA
Please note that once the [MR](https://git.drupalcode.org/project/sitestudio_gin/-/merge_requests/9) for Drupal 11 compatibility of the `sitestudio_gin` module is completed, the [vsc](https://github.com/acquia/acquia_cms/pull/1865/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R238-R241) path added in `composer.json` for the `sitestudio_gin` module will be removed.
> ACMS-3947: Drupal 11 compatibility fixes for SiteStudio Config Management.

- composer.json
- composer.lock
**Motivation**
SiteStudio Gin module is available with D11 compatible stable release.
Update SiteStudio Gin module to latest stable release.
NA
Create D11 project.
SiteStudio Gin module using `composer require drupal/sitestudio_gin -W`.
Install sitestudio_gin module.
Verify module installed sucessfully.
> ACMS-000: Update SiteStudio Gin module to stable release.

- composer.json
- composer.lock
- modules/acquia_cms_common/composer.json
- modules/acquia_cms_toolbar/composer.json
- modules/acquia_cms_tour/css/acquia_cms_tour_dashboard.css
- modules/acquia_cms_tour/src/Plugin/AcquiaCmsTour/GoogleTagManagerForm.php
- modules/acquia_cms_tour/tests/src/Functional/GoogleTagManager.php
**Motivation**
Fixes #ACMS-4229
introduction of form from google_tag module which includes usage of google tag id now.
install site using this branch and run drush site:install and enable acquia_cms_tour
visit page /admin/tour/dashboard and check section google tag
> ACMS-4229: Update google_tag form on tour dashboard.

- modules/acquia_cms_article/.gitlab-ci.yml
- modules/acquia_cms_audio/.gitlab-ci.yml
- modules/acquia_cms_component/.gitlab-ci.yml
- modules/acquia_cms_dam/.gitlab-ci.yml
- modules/acquia_cms_document/.gitlab-ci.yml
- modules/acquia_cms_event/.gitlab-ci.yml
- modules/acquia_cms_headless/.gitlab-ci.yml
- modules/acquia_cms_image/.gitlab-ci.yml
- modules/acquia_cms_page/.gitlab-ci.yml
- modules/acquia_cms_person/.gitlab-ci.yml
- modules/acquia_cms_place/.gitlab-ci.yml
- modules/acquia_cms_search/.gitlab-ci.yml
- modules/acquia_cms_site_studio/.gitlab-ci.yml
- modules/acquia_cms_starter/.gitlab-ci.yml
- modules/acquia_cms_toolbar/.gitlab-ci.yml
- modules/acquia_cms_tour/.gitlab-ci.yml
- modules/acquia_cms_video/.gitlab-ci.yml
**Motivation**
Fixes #ACMS-4288
ACMS-4288: Fix GitLab CI pipelines of Drupal Starter Kit Modules.
NA
Verify CI on project page.
> ACMS-4288: Fix GitLab CI pipelines of Drupal Starter Kit Modules.

- composer.json
- composer.lock
- modules/acquia_cms_common/tests/src/Functional/FilterFormatTest.php
- modules/acquia_cms_site_studio/acquia_cms_site_studio.info.yml
- modules/acquia_cms_site_studio/acquia_cms_site_studio.install
- modules/acquia_cms_site_studio/acquia_cms_site_studio.module
- modules/acquia_cms_site_studio/config/install/user.role.developer.yml
- modules/acquia_cms_site_studio/src/Facade/ConfigHandlerFacade.php
- modules/acquia_cms_site_studio/tests/acquia_cms_site_studio_test/acquia_cms_site_studio_test.info.yml
- modules/acquia_cms_site_studio/tests/acquia_cms_site_studio_test/config/install/core.entity_view_mode.media.embedded.yml
- modules/acquia_cms_site_studio/tests/acquia_cms_site_studio_test/config/install/editor.editor.filtered_html.yml
- modules/acquia_cms_site_studio/tests/acquia_cms_site_studio_test/config/install/editor.editor.full_html.yml
- modules/acquia_cms_site_studio/tests/acquia_cms_site_studio_test/config/install/filter.format.filtered_html.yml
- modules/acquia_cms_site_studio/tests/acquia_cms_site_studio_test/config/install/filter.format.full_html.yml
- modules/acquia_cms_site_studio/tests/src/Functional/ExistingEditorPermissionsTest.php
- modules/acquia_cms_site_studio/tests/src/Functional/FilterFormatCohesionTest.php
- modules/acquia_cms_site_studio/tests/src/Functional/NewEditorPermissionsTest.php
- modules/acquia_cms_site_studio/tests/src/Functional/SiteStudioPermissionsTest.php
- modules/acquia_cms_site_studio/tests/src/Traits/PermissionsTrait.php
- modules/acquia_cms_site_studio/tests/src/fixtures/permissions/basic/user.role.developer.yml
- tests/src/fixtures/permissions/integrated/user.role.developer.yml
- tests/src/fixtures/permissions/integrated/user.role.site_builder.yml
**Motivation**
Fixes #[ACMS-4237](https://acquia.atlassian.net/browse/ACMS-4237)
Remove Dependency of acquia_cms_common from Site Studio.
NA
> ACMS-4237: Remove Dependency of acquia_cms_common from Site Studio.

- composer.lock
- modules/acquia_cms_common/composer.json
This pull request updates the version constraint for the `drupal/autologout` dependency in the `composer.json` file of the `acquia_cms_common` module. The change ensures compatibility with both version 1 and version 2 of the dependency.
Dependency updates:
* [`modules/acquia_cms_common/composer.json`](diffhunk://#diff-23e1fe87680badf5f17710c96b8c12298ab8276162fb40fb74fb937897c17925L12-R12): Updated the `drupal/autologout` dependency version constraint from `^1.4` to `^1.4 || ^2` to allow compatibility with version 2.
> ACMS-4497: Upgrade support for Autologout module in acquia_cms_common.

- composer.json
- composer.lock
- modules/acquia_cms_site_studio/composer.json
This pull request updates the `composer.json` file in the `modules/acquia_cms_site_studio` directory to expand compatibility for specific dependencies.
Dependency updates:
* [`acquia/cohesion`](diffhunk://#diff-41be90a640beeb89524b54a073b9478153cb85d0b04472e3d617cd3ad8a921caL7-R8): Added support for version `~8.2.0` in the `require` section.
* [`acquia/cohesion-theme`](diffhunk://#diff-41be90a640beeb89524b54a073b9478153cb85d0b04472e3d617cd3ad8a921caL7-R8): Added support for version `~8.2.0` in the `require` section.
> Update Starter kits compatible with Site Studio 8.2.0-beta2 version.
